import { ACTION_TYPES } from "lib/Constants";

const {
  LOAD_CLIENT_WORKFLOW_SUCCESS,
  LOAD_CLIENT_WORKFLOW_CANVIEW,
  LOAD_CLIENT_WORKFLOW_CANADD,
  CREATE_CLIENT_WORKFLOW_SUCCESS,
  LOAD_CLIENT_WORKFLOW_COUNT_SUCCESS,
} = ACTION_TYPES;

export default {
  LOAD_CLIENT_WORKFLOW_SUCCESS: LOAD_CLIENT_WORKFLOW_SUCCESS,
  LOAD_CLIENT_WORKFLOW_CANVIEW: LOAD_CLIENT_WORKFLOW_CANVIEW,
  LOAD_CLIENT_WORKFLOW_CANADD: LOAD_CLIENT_WORKFLOW_CANADD,
  CREATE_CLIENT_WORKFLOW_SUCCESS: CREATE_CLIENT_WORKFLOW_SUCCESS,
  LOAD_CLIENT_WORKFLOW_COUNT_SUCCESS: LOAD_CLIENT_WORKFLOW_COUNT_SUCCESS,
};
