package com.scnsoft.eldermark.entity.security;

import com.scnsoft.eldermark.entity.Employee;

import java.util.function.Predicate;

/**
 * Permissions to be assigned to user roles.
 * <p>
 * Typical naming is the following: {entity}_{action}_IF_{condition}.
 * <p>
 * Care team members conditions will have additional affiliation restrictions ({aff}):
 * REGULAR - regular only (user and client are in the same organization),
 * PRIMARY - primary only (user and client are in different organizations),
 * RP - both regular and primary (no restrictions to user's and client's organizations and communities)
 * <p>
 * Care team members conditions will have additional consent (client opt in/opt out restrictions ({cons}):
 * CURRENT - current only
 * ON_HOLD - on hold only
 * CO - both current and on hold (i.e. no consent restrictions)
 * <p>
 * Most common conditions:
 * x. ASSOCIATED_ORGANIZATION - user's organization
 * x. ASSOCIATED_COMMUNITY - user's community
 * x. FROM_AFFILIATED_ORGANIZATION - entity is in primary community of any community from user's organization
 * x. FROM_AFFILIATED_COMMUNITY - entity is in primary community of user's community
 * x. {cons}_{aff}_COMMUNITY_CTM - user is community care team member of client entity is tied to
 * with affiliation restrictions in coded in {aff} and client consent restriction coded in {cons}
 * x. {cons}_{aff}_CLIENT_CTM - user is client care team member of client entity is tied to
 * with affiliation restrictions in coded in {aff} and client consent restriction coded in {cons}
 * x. ADDED_BY_SELF - entity is added by user
 * x. CLIENT_ADDED_BY_SELF - entity is tied to client added by self
 * x. SELF_RECORD - entity is tied to self resident of user record.
 */
public enum Permission {
    // ====================================================== Roles ====================================================
    ROLE_SUPER_ADMINISTRATOR,
    ROLE_ORGANIZATION_ADMINISTRATOR,
    ROLE_COMMUNITY_ADMINISTRATOR,

    ROLE_CARE_COORDINATOR,
    ROLE_CASE_MANAGER,
    ROLE_COMMUNITY_PROVIDER,
    ROLE_PARENT_GUARDIAN,
    ROLE_PERSON_RECEIVING_SERVICES,
    ROLE_PRIMARY_PHYSICIAN,
    ROLE_BEHAVIORAL_HEALTH,
    ROLE_SERVICE_PROVIDER,
    ROLE_PHARMACIST,
    ROLE_PHARMACY_TECHNICIAN,
    ROLE_NURSE,
    ROLE_TELE_HEALTH_NURSE,
    ROLE_EXTERNAL_USER,
    ROLE_HCA,
    ROLE_CONTENT_CREATOR,
    ROLE_MARKETER,

    ROLE_UNKNOWN,

    // =================================================== Organizations ===============================================
    ORGANIZATION_VIEW_IN_LIST_ALL,
    ORGANIZATION_VIEW_IN_LIST_IF_ASSOCIATED_ORGANIZATION,
    ORGANIZATION_VIEW_IN_LIST_IF_FROM_AFFILIATED_ORGANIZATION,
    ORGANIZATION_VIEW_IN_LIST_IF_FROM_AFFILIATED_COMMUNITY,
    ORGANIZATION_VIEW_IN_LIST_IF_CO_RP_COMMUNITY_CTM,
    ORGANIZATION_VIEW_IN_LIST_IF_CO_RP_CLIENT_CTM,
    ORGANIZATION_VIEW_IN_LIST_EXTERNAL_REFERRAL_REQUEST,

    ORGANIZATION_VIEW_DETAILS_ALL,
    ORGANIZATION_VIEW_DETAILS_IF_ASSOCIATED_ORGANIZATION,
    ORGANIZATION_VIEW_DETAILS_IF_FROM_AFFILIATED_ORGANIZATION,
    ORGANIZATION_VIEW_DETAILS_IF_FROM_AFFILIATED_COMMUNITY,
    ORGANIZATION_VIEW_DETAILS_IF_CO_RP_COMMUNITY_CTM,
    ORGANIZATION_VIEW_DETAILS_IF_CO_RP_CLIENT_CTM,

    ORGANIZATION_VIEW_LOGO_ALL,
    ORGANIZATION_VIEW_LOGO_IF_ASSOCIATED_ORGANIZATION,
    ORGANIZATION_VIEW_LOGO_IF_FROM_AFFILIATED_ORGANIZATION,
    ORGANIZATION_VIEW_LOGO_IF_FROM_AFFILIATED_COMMUNITY,
    ORGANIZATION_VIEW_LOGO_IF_CO_RP_COMMUNITY_CTM,
    ORGANIZATION_VIEW_LOGO_IF_CO_RP_CLIENT_CTM,
    ORGANIZATION_VIEW_LOGO_IF_ACCESSIBLE_CLIENT_CTM_ASSOCIATED_ORGANIZATION,
    ORGANIZATION_VIEW_LOGO_IF_ACCESSIBLE_COMMUNITY_CTM_ASSOCIATED_ORGANIZATION,
    ORGANIZATION_VIEW_LOGO_IF_FROM_PARTNER_COMMUNITY_ORGANIZATION,
    ORGANIZATION_VIEW_LOGO_IF_ACCESSIBLE_MEDICATION_IN_ORGANIZATION,

    ORGANIZATION_EDIT_ALL,
    ORGANIZATION_EDIT_IF_ASSOCIATED_ORGANIZATION,

    ORGANIZATION_EDIT_FEATURES_ALL,

    ORGANIZATION_EDIT_AFFILIATED_RELATIONSHIPS_ALL,
    ORGANIZATION_EDIT_AFFILIATED_RELATIONSHIPS_IF_ASSOCIATED_ORGANIZATION,

    ORGANIZATION_CONFIGURE_MARKETPLACE_ALL,
    ORGANIZATION_CONFIGURE_MARKETPLACE_IF_ASSOCIATED_ORGANIZATION,

    ORGANIZATION_ADD_ALL,

    // ============================================= Document categories ===============================================
    DOCUMENT_CATEGORY_VIEW_ALL,
    DOCUMENT_CATEGORY_VIEW_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_CATEGORY_VIEW_IF_FROM_AFFILIATED_ORGANIZATION,
    DOCUMENT_CATEGORY_VIEW_IF_FROM_AFFILIATED_COMMUNITY,
    DOCUMENT_CATEGORY_VIEW_IF_CO_RP_COMMUNITY_CTM,
    DOCUMENT_CATEGORY_VIEW_IF_CO_RP_CLIENT_CTM,
    DOCUMENT_CATEGORY_VIEW_IF_SELF_RECORD,

    DOCUMENT_CATEGORY_MANAGE_ALL,
    DOCUMENT_CATEGORY_MANAGE_IF_ASSOCIATED_ORGANIZATION,

    // ================================================== Communities ==================================================
    COMMUNITY_VIEW_IN_LIST_ALL,
    COMMUNITY_VIEW_IN_LIST_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_VIEW_IN_LIST_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_VIEW_IN_LIST_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_VIEW_IN_LIST_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_VIEW_IN_LIST_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_VIEW_IN_LIST_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_VIEW_IN_LIST_IF_EXTERNAL_REFERRAL_REQUEST,

    COMMUNITY_VIEW_DETAILS_ALL,
    COMMUNITY_VIEW_DETAILS_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_VIEW_DETAILS_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_VIEW_DETAILS_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_VIEW_DETAILS_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_VIEW_DETAILS_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_VIEW_DETAILS_IF_CO_RP_CLIENT_CTM,

    COMMUNITY_VIEW_LOGO_ALL,
    COMMUNITY_VIEW_LOGO_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_VIEW_LOGO_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_VIEW_LOGO_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_VIEW_LOGO_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_VIEW_LOGO_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_VIEW_LOGO_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_VIEW_LOGO_IF_ACCESSIBLE_CLIENT_CTM_ASSOCIATED_COMMUNITY,
    COMMUNITY_VIEW_LOGO_IF_ACCESSIBLE_COMMUNITY_CTM_ASSOCIATED_COMMUNITY,
    COMMUNITY_VIEW_LOGO_IF_FROM_PARTNER_COMMUNITY_ORGANIZATION,
    COMMUNITY_VIEW_LOGO_IF_ACCESSIBLE_MEDICATION_IN_COMMUNITY,

    COMMUNITY_ADD_ALL,
    COMMUNITY_ADD_IF_ASSOCIATED_ORGANIZATION,

    COMMUNITY_EDIT_ALL,
    COMMUNITY_EDIT_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_EDIT_IF_ASSOCIATED_COMMUNITY,

    COMMUNITY_EDIT_SIGNATURE_CONFIG_ALL,
    COMMUNITY_EDIT_SIGNATURE_CONFIG_IF_ASSOCIATED_ORGANIZATION,

    COMMUNITY_CONFIGURE_MARKETPLACE_ALL,
    COMMUNITY_CONFIGURE_MARKETPLACE_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_CONFIGURE_MARKETPLACE_IF_ASSOCIATED_COMMUNITY,

    // ================================================ Clients ========================================================

    CLIENT_VIEW_IN_LIST_ALL,
    CLIENT_VIEW_IN_LIST_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_VIEW_IN_LIST_IF_ASSOCIATED_COMMUNITY,
    CLIENT_VIEW_IN_LIST_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_VIEW_IN_LIST_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_VIEW_IN_LIST_IF_CO_RP_CLIENT_CTM,
    CLIENT_VIEW_IN_LIST_IF_CO_RP_COMMUNITY_CTM,
    CLIENT_VIEW_IN_LIST_IF_ADDED_BY_SELF,
    CLIENT_VIEW_IN_LIST_IF_SELF_RECORD,
    CLIENT_VIEW_IN_LIST_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    CLIENT_VIEW_ALL_EXCEPT_OPTED_OUT,
    CLIENT_VIEW_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_VIEW_IF_ASSOCIATED_COMMUNITY,
    CLIENT_VIEW_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_VIEW_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_VIEW_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_VIEW_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_VIEW_OPTED_IN_IF_ADDED_BY_SELF,
    CLIENT_VIEW_IF_SELF_RECORD,
    CLIENT_VIEW_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    CLIENT_ADD_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_ADD_IF_ASSOCIATED_COMMUNITY,
    CLIENT_ADD_IF_REGULAR_COMMUNITY_CTM,

    CLIENT_EDIT_ALL_EXCEPT_OPTED_OUT,
    CLIENT_EDIT_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_EDIT_IF_ASSOCIATED_COMMUNITY,
    CLIENT_EDIT_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_EDIT_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_EDIT_OPTED_IN_IF_ADDED_BY_SELF,

    CLIENT_EDIT_SSN_ALL_EXPECT_OPTED_OUT,
    CLIENT_EDIT_SSN_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_EDIT_SSN_IF_ASSOCIATED_COMMUNITY,
    CLIENT_EDIT_SSN_OPTED_IN_IF_ADDED_BY_SELF,

    // =============================================== Client Expenses =================================================

    CLIENT_EXPENSE_VIEW_ALL_EXCEPT_OPTED_OUT,
    CLIENT_EXPENSE_VIEW_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_EXPENSE_VIEW_IF_ASSOCIATED_COMMUNITY,
    CLIENT_EXPENSE_VIEW_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_EXPENSE_VIEW_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_EXPENSE_VIEW_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_EXPENSE_VIEW_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_EXPENSE_VIEW_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    CLIENT_EXPENSE_VIEW_IF_SELF_RECORD,

    CLIENT_EXPENSE_ADD_ALL_EXCEPT_OPTED_OUT,
    CLIENT_EXPENSE_ADD_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_EXPENSE_ADD_IF_ASSOCIATED_COMMUNITY,
    CLIENT_EXPENSE_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_EXPENSE_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_EXPENSE_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    // ================================================ Clients rides ==================================================
    CLIENT_REQUEST_RIDE_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REQUEST_RIDE_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REQUEST_RIDE_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REQUEST_RIDE_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_REQUEST_RIDE_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REQUEST_RIDE_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    CLIENT_REQUEST_RIDE_IF_SELF_CLIENT_RECORD,

    CLIENT_VIEW_RIDE_HISTORY_ALL_EXCEPT_OPTED_OUT,
    CLIENT_VIEW_RIDE_HISTORY_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_VIEW_RIDE_HISTORY_IF_ASSOCIATED_COMMUNITY,
    CLIENT_VIEW_RIDE_HISTORY_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_VIEW_RIDE_HISTORY_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_VIEW_RIDE_HISTORY_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_VIEW_RIDE_HISTORY_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_VIEW_RIDE_HISTORY_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_VIEW_RIDE_HISTORY_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    CLIENT_VIEW_RIDE_HISTORY_IF_SELF_CLIENT_RECORD,

    // =============================================== Prospects =======================================================

    PROSPECT_VIEW_IN_LIST_ALL,
    PROSPECT_VIEW_IN_LIST_IF_ASSOCIATED_ORGANIZATION,
    PROSPECT_VIEW_IN_LIST_IF_ASSOCIATED_COMMUNITY,
    PROSPECT_VIEW_IN_LIST_IF_CO_REGULAR_CTM,

    PROSPECT_ADD_ALL,
    PROSPECT_ADD_IF_ASSOCIATED_ORGANIZATION,
    PROSPECT_ADD_IF_ASSOCIATED_COMMUNITY,

    PROSPECT_EDIT_ALL,
    PROSPECT_EDIT_IF_ASSOCIATED_ORGANIZATION,
    PROSPECT_EDIT_IF_ASSOCIATED_COMMUNITY,
    PROSPECT_EDIT_IF_ADDED_BY_SELF,

    PROSPECT_VIEW_ALL,
    PROSPECT_VIEW_IF_ASSOCIATED_ORGANIZATION,
    PROSPECT_VIEW_IF_ASSOCIATED_COMMUNITY,
    PROSPECT_VIEW_IF_CO_REGULAR_CTM,
    PROSPECT_VIEW_IF_ADDED_BY_SELF,

    // ================================================= Notes =========================================================
    NOTE_VIEW_MERGED_ALL_EXCEPT_OPTED_OUT,
    NOTE_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    NOTE_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    NOTE_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    NOTE_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    NOTE_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    NOTE_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    NOTE_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    NOTE_VIEW_MERGED_IF_SELF_CLIENT_RECORD,
    NOTE_VIEW_MERGED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    NOTE_ADD_ALL_EXCEPT_OPTED_OUT,
    NOTE_ADD_IF_ASSOCIATED_ORGANIZATION,
    NOTE_ADD_IF_ASSOCIATED_COMMUNITY,
    NOTE_ADD_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    NOTE_ADD_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    NOTE_ADD_IF_CURRENT_RP_COMMUNITY_CTM,
    NOTE_ADD_IF_CURRENT_RP_CLIENT_CTM,
    NOTE_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    NOTE_ADD_IF_SELF_CLIENT_RECORD,
    NOTE_ADD_IF_CLIENT_FOUND_IN_RECORD_SEARCH,
    GROUP_NOTE_ADD_ALLOWED,

    NOTE_EDIT_ADDED_BY_SELF_ALL_EXCEPT_OPTED_OUT,
    NOTE_EDIT_ADDED_BY_SELF_IF_ASSOCIATED_ORGANIZATION,
    NOTE_EDIT_ADDED_BY_SELF_IF_ASSOCIATED_COMMUNITY,
    NOTE_EDIT_ADDED_BY_SELF_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    NOTE_EDIT_ADDED_BY_SELF_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    NOTE_EDIT_ADDED_BY_SELF_IF_CURRENT_RP_COMMUNITY_CTM,
    NOTE_EDIT_ADDED_BY_SELF_IF_CURRENT_RP_CLIENT_CTM,
    NOTE_EDIT_ADDED_BY_SELF_OPTED_IN_IF_ADDED_BY_SELF,
    NOTE_EDIT_ADDED_BY_SELF_IF_SELF_CLIENT_RECORD,
    NOTE_EDIT_ADDED_BY_SELF_IF_CLIENT_FOUND_IN_RECORD_SEARCH,
    GROUP_NOTE_EDIT_ALLOWED,

    // ============================================== Events ===========================================================
    EVENT_VIEW_MERGED_ALL_EXCEPT_OPTED_OUT_CLIENT,
    EVENT_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    EVENT_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    EVENT_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    EVENT_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    EVENT_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    EVENT_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    EVENT_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    EVENT_VIEW_MERGED_IF_SELF_CLIENT_RECORD,
    EVENT_VIEW_MERGED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    EVENT_ADD_EXCEPT_OPTED_OUT_CLIENT,
    EVENT_ADD_IF_ASSOCIATED_ORGANIZATION,
    EVENT_ADD_IF_ASSOCIATED_COMMUNITY,
    EVENT_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    EVENT_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    EVENT_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    EVENT_ADD_IF_SELF_CLIENT_RECORD,
    EVENT_ADD_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    // ============================================= Contacts ==========================================================
    CONTACT_VIEW_IF_ASSOCIATED_ORGANIZATION,
    CONTACT_VIEW_IF_CREATED_BY_SELF,
    CONTACT_VIEW_IF_SELF_RECORD,

    CONTACT_ADD_BY_MATRIX_ALL,
    CONTACT_ADD_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    CONTACT_ADD_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,

    CONTACT_EDIT_BY_MATRIX_ALL,
    CONTACT_EDIT_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    CONTACT_EDIT_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    CONTACT_EDIT_BY_MATRIX_IF_CREATED_BY_SELF,
    CONTACT_EDIT_BY_MATRIX_IF_SELF_RECORD,

    // ============================================= Client care team ==========================================================

    //details are needed to view edit form. Allow to open edit form for direct clients only (not merged)
    CLIENT_CARE_TEAM_VIEW_VISIBLE_ALL_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_OPTED_IN_IF_CLIENT_ADDED_BY_SELF,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_SELF_CLIENT_RECORD,
    CLIENT_CARE_TEAM_VIEW_VISIBLE_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_ALL_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_OPTED_IN_IF_CLIENT_ADDED_BY_SELF,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_SELF_CLIENT_RECORD,
    CLIENT_CARE_TEAM_VIEW_IN_LIST_MERGED_VISIBLE_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_ALL_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_CURRENT_RP_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_CURRENT_RP_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    CLIENT_CARE_TEAM_ADD_VISIBLE_BY_MATRIX_IF_SELF_CLIENT_RECORD_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_REGULAR_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_ADD_VISIBLE_RP_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,

    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_ALL_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_CURRENT_RP_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_CURRENT_RP_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_OPTED_IN_IF_CLIENT_ADDED_BY_SELF,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_SELF_CLIENT_RECORD_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_BY_MATRIX_IF_PRIMARY_SELF_CARE_TEAM_RECORD_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_REGULAR_BY_MATRIX_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_EDIT_VISIBLE_RP_BY_MATRIX_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,

    CLIENT_CARE_TEAM_DELETE_VISIBLE_ALL_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_CURRENT_RP_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_CLIENT_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_CURRENT_RP_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_CURRENT_REGULAR_COMMUNITY_CTM_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_OPTED_IN_IF_CLIENT_ADDED_BY_SELF,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_SELF_CLIENT_RECORD_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_BY_MATRIX_IF_PRIMARY_SELF_CARE_TEAM_RECORD_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_REGULAR_BY_MATRIX_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,
    CLIENT_CARE_TEAM_DELETE_VISIBLE_RP_BY_MATRIX_IF_CLIENT_FOUND_IN_RECORD_SEARCH_EXCEPT_OPTED_OUT,

    CLIENT_CARE_TEAM_INVITATION_ADD_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_INVITATION_ADD_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_INVITATION_ADD_IF_SELF_CLIENT_RECORD,

    CLIENT_CARE_TEAM_INVITATION_VIEW_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_INVITATION_VIEW_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_INVITATION_VIEW_IF_SELF_CLIENT_RECORD,
    CLIENT_CARE_TEAM_INVITATION_VIEW_IF_SELF_TARGET_EMPLOYEE,

    CLIENT_CARE_TEAM_INVITATION_RESEND_CANCEL_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_CARE_TEAM_INVITATION_RESEND_CANCEL_IF_ASSOCIATED_COMMUNITY,
    CLIENT_CARE_TEAM_INVITATION_RESEND_CANCEL_IF_SELF_CLIENT_RECORD,

    CLIENT_CARE_TEAM_INVITATION_ACCEPT_DECLINE_IF_SELF_TARGET_EMPLOYEE,

    // ========================================= Community care team ===================================================

    COMMUNITY_CARE_TEAM_VIEW_ALL,
    COMMUNITY_CARE_TEAM_VIEW_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_VIEW_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_VIEW_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_VIEW_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_VIEW_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_VIEW_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_VIEW_IF_CLIENT_ADDED_BY_SELF,
    COMMUNITY_CARE_TEAM_VIEW_IF_SELF_RECORD,

    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_ALL,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_CO_REGULAR_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_CLIENT_ADDED_BY_SELF,
    COMMUNITY_CARE_TEAM_ADD_BY_MATRIX_IF_SELF_CLIENT_RECORD,

    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_ALL,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_CO_REGULAR_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_CLIENT_ADDED_BY_SELF,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_SELF_CLIENT_RECORD,
    COMMUNITY_CARE_TEAM_EDIT_BY_MATRIX_IF_PRIMARY_SELF_CARE_TEAM_RECORD,

    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_ALL,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_FROM_AFFILIATED_ORGANIZATION,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_FROM_AFFILIATED_COMMUNITY,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_CO_RP_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_CO_REGULAR_CLIENT_CTM,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_CO_RP_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_CLIENT_ADDED_BY_SELF,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_SELF_CLIENT_RECORD,
    COMMUNITY_CARE_TEAM_DELETE_BY_MATRIX_IF_PRIMARY_SELF_CARE_TEAM_RECORD,

    // ============================================= Service Plans =====================================================

    SERVICE_PLAN_VIEW_ALL_EXCEPT_OPTED_OUT,
    SERVICE_PLAN_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    SERVICE_PLAN_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    SERVICE_PLAN_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    SERVICE_PLAN_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    SERVICE_PLAN_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    SERVICE_PLAN_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    SERVICE_PLAN_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    SERVICE_PLAN_ADD_ALL_EXCEPT_OPTED_OUT,
    SERVICE_PLAN_ADD_IF_ASSOCIATED_ORGANIZATION,
    SERVICE_PLAN_ADD_IF_ASSOCIATED_COMMUNITY,
    SERVICE_PLAN_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    SERVICE_PLAN_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    SERVICE_PLAN_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    SERVICE_PLAN_EDIT_ALL_EXCEPT_OPTED_OUT,
    SERVICE_PLAN_EDIT_IF_ASSOCIATED_ORGANIZATION,
    SERVICE_PLAN_EDIT_IF_ASSOCIATED_COMMUNITY,
    SERVICE_PLAN_EDIT_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    SERVICE_PLAN_EDIT_ADDED_BY_SELF_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    SERVICE_PLAN_EDIT_IF_CURRENT_REGULAR_CLIENT_CTM,
    SERVICE_PLAN_EDIT_ADDED_BY_SELF_IF_CURRENT_REGULAR_CLIENT_CTM,
    SERVICE_PLAN_EDIT_ADDED_BY_SELF_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    // ============================================= Assessments =======================================================

    ASSESSMENT_VIEW_ALL_TYPES_ALLOWED,
    ASSESSMENT_VIEW_HIDDEN_ALLOWED,

    ASSESSMENT_HIDE_ALL_EXCEPT_OPTED_OUT,
    ASSESSMENT_HIDE_IF_ASSOCIATED_ORGANIZATION,

    ASSESSMENT_RESTORE_ALL_EXCEPT_OPTED_OUT,
    ASSESSMENT_RESTORE_IF_ASSOCIATED_ORGANIZATION,

    ASSESSMENT_VIEW_ALL_EXCEPT_OPTED_OUT,
    ASSESSMENT_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    ASSESSMENT_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    ASSESSMENT_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    ASSESSMENT_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    ASSESSMENT_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    ASSESSMENT_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    ASSESSMENT_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    ASSESSMENT_VIEW_MERGED_IF_SELF_RECORD,

    ASSESSMENT_ADD_ALL_EXCEPT_OPTED_OUT,
    ASSESSMENT_ADD_IF_ASSOCIATED_ORGANIZATION,
    ASSESSMENT_ADD_IF_ASSOCIATED_COMMUNITY,
    ASSESSMENT_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    ASSESSMENT_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    ASSESSMENT_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    ASSESSMENT_EDIT_ALL_EXCEPT_OPTED_OUT,
    ASSESSMENT_EDIT_IF_ASSOCIATED_ORGANIZATION,
    ASSESSMENT_EDIT_ADDED_BY_SELF_IF_ASSOCIATED_COMMUNITY,
    ASSESSMENT_EDIT_ADDED_BY_SELF_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    ASSESSMENT_EDIT_ADDED_BY_SELF_IF_CURRENT_REGULAR_CLIENT_CTM,
    ASSESSMENT_EDIT_ADDED_BY_SELF_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    ASSESSMENT_EDIT_IF_CURRENT_REGULAR_CLIENT_CTM,
    ASSESSMENT_EDIT_IF_CURRENT_REGULAR_COMMUNITY_CTM,

    // =============================================== Reports =======================================================
    REPORT_GENERATION_ALLOWED,
    CLIENT_REPORT_GENERATION_IN_TUNE_ALLOWED,

    // ============================================= Marketplace =======================================================

    MARKETPLACE_VIEW_NOT_DISCOVERABLE_ALLOWED,
    MARKETPLACE_VIEW_ALL,
    MARKETPLACE_VIEW_IF_ASSOCIATED_ORGANIZATION,
    MARKETPLACE_VIEW_IF_FROM_PARTNER_COMMUNITY_ORGANIZATION,

    MARKETPLACE_EDIT_FEATURED_PARTNER_PROVIDER_IF_ASSOCIATED_ORGANIZATION,
    MARKETPLACE_EDIT_FEATURED_PARTNER_PROVIDER_IF_ASSOCIATED_COMMUNITY,

    MARKETPLACE_VIEW_PARTNER_PROVIDER_ALL,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_ASSOCIATED_ORGANIZATION,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_ASSOCIATED_COMMUNITY,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_FROM_PARTNER_COMMUNITY_ORGANIZATION,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_FROM_AFFILIATED_ORGANIZATION,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_FROM_AFFILIATED_COMMUNITY,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_CO_RP_COMMUNITY_CTM,
    MARKETPLACE_VIEW_PARTNER_PROVIDER_IF_CO_RP_CLIENT_CTM,

    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_ALL,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_ASSOCIATED_ORGANIZATION,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_ASSOCIATED_COMMUNITY,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_FROM_AFFILIATED_ORGANIZATION,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_FROM_AFFILIATED_COMMUNITY,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_CO_RP_COMMUNITY_CTM,
    MARKETPLACE_VIEW_FEATURED_PARTNER_PROVIDER_IF_CO_RP_CLIENT_CTM,

    // ============================================= Documents =========================================================

    DOCUMENT_VIEW_MERGED_SHARED_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_VIEW_MERGED_SHARED_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_VIEW_MERGED_SHARED_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_VIEW_MERGED_SHARED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    DOCUMENT_VIEW_MERGED_SHARED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    DOCUMENT_VIEW_MERGED_SHARED_IF_CURRENT_RP_COMMUNITY_CTM,
    DOCUMENT_VIEW_MERGED_SHARED_IF_CURRENT_RP_CLIENT_CTM,
    DOCUMENT_VIEW_MERGED_SHARED_IF_SELF_RECORD,
    DOCUMENT_VIEW_MERGED_SHARED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    DOCUMENT_VIEW_MERGED_SHARED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    DOCUMENT_VIEW_CCD_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_VIEW_CCD_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_VIEW_CCD_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_VIEW_CCD_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    DOCUMENT_VIEW_CCD_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    DOCUMENT_VIEW_CCD_IF_CURRENT_RP_COMMUNITY_CTM,
    DOCUMENT_VIEW_CCD_IF_CURRENT_RP_CLIENT_CTM,
    DOCUMENT_VIEW_CCD_IF_SELF_RECORD,
    DOCUMENT_VIEW_CCD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    DOCUMENT_VIEW_CCD_IF_SHARED_BY_REFERRAL,
    DOCUMENT_VIEW_CCD_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    DOCUMENT_VIEW_FACESHEET_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_VIEW_FACESHEET_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_VIEW_FACESHEET_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_VIEW_FACESHEET_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    DOCUMENT_VIEW_FACESHEET_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    DOCUMENT_VIEW_FACESHEET_IF_CURRENT_RP_COMMUNITY_CTM,
    DOCUMENT_VIEW_FACESHEET_IF_CURRENT_RP_CLIENT_CTM,
    DOCUMENT_VIEW_FACESHEET_IF_SELF_RECORD,
    DOCUMENT_VIEW_FACESHEET_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    DOCUMENT_VIEW_FACESHEET_IF_SHARED_BY_REFERRAL,
    DOCUMENT_VIEW_FACESHEET_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    DOCUMENT_VIEW_SERVICE_PLAN_PDF_IF_SHARED_BY_REFERRAL,

    DOCUMENT_ADD_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_ADD_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_ADD_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    DOCUMENT_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    DOCUMENT_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    DOCUMENT_ADD_IF_CLIENT_FOUND_IN_RECORD_SEARCH,
    DOCUMENT_ADD_IF_SELF_RECORD,

    DOCUMENT_MODIFY_SHARED_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_MODIFY_SHARED_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_MODIFY_SHARED_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_MODIFY_SHARED_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    DOCUMENT_MODIFY_SHARED_IF_CURRENT_REGULAR_CLIENT_CTM,
    DOCUMENT_MODIFY_SHARED_ADDED_BY_SELF_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    DOCUMENT_MODIFY_SHARED_ADDED_BY_SELF_IF_CURRENT_REGULAR_CLIENT_CTM,
    DOCUMENT_MODIFY_SHARED_ADDED_BY_SELF_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    DOCUMENT_MODIFY_SHARED_ADDED_BY_SELF_IF_CLIENT_FOUND_IN_RECORD_SEARCH,
    DOCUMENT_MODIFY_SHARED_ADDED_BY_SELF_IF_SELF_RECORD,

    // ========================================== Community Files ======================================================

    COMMUNITY_FILE_ADD_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FILE_ADD_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FILE_ADD_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FILE_ADD_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FILE_VIEW_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FILE_VIEW_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FILE_VIEW_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FILE_VIEW_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FILE_EDIT_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FILE_EDIT_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FILE_EDIT_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FILE_EDIT_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FILE_DELETE_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FILE_DELETE_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FILE_DELETE_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FILE_DELETE_IF_CO_RP_COMMUNITY_CTM,

    // ========================================== Community Folders ====================================================

    COMMUNITY_FOLDER_VIEW_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FOLDER_VIEW_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FOLDER_VIEW_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FOLDER_VIEW_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FOLDER_ADD_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FOLDER_ADD_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FOLDER_ADD_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FOLDER_ADD_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_TEMPLATE_FOLDER_ADD_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_TEMPLATE_FOLDER_ADD_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_TEMPLATE_FOLDER_ADD_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_TEMPLATE_FOLDER_ADD_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FOLDER_EDIT_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FOLDER_EDIT_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FOLDER_EDIT_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FOLDER_EDIT_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_TEMPLATE_FOLDER_EDIT_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_TEMPLATE_FOLDER_EDIT_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_TEMPLATE_FOLDER_EDIT_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_TEMPLATE_FOLDER_EDIT_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_FOLDER_DELETE_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_FOLDER_DELETE_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_FOLDER_DELETE_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_FOLDER_DELETE_IF_CO_RP_COMMUNITY_CTM,

    COMMUNITY_TEMPLATE_FOLDER_DELETE_IF_ASSOCIATED_ORGANIZATION,
    COMMUNITY_TEMPLATE_FOLDER_DELETE_IF_ASSOCIATED_COMMUNITY,
    COMMUNITY_TEMPLATE_FOLDER_DELETE_IF_CO_REGULAR_COMMUNITY_CTM,
    COMMUNITY_TEMPLATE_FOLDER_DELETE_IF_CO_RP_COMMUNITY_CTM,

    // ========================================== Document signature ===================================================

    DOCUMENT_TEMPLATE_VIEW_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_TEMPLATE_VIEW_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_TEMPLATE_VIEW_IF_CO_RP_COMMUNITY_CTM,
    DOCUMENT_TEMPLATE_VIEW_IF_CO_REGULAR_COMMUNITY_CTM,
    DOCUMENT_TEMPLATE_VIEW_IF_CURRENT_RP_CLIENT_CTM,
    DOCUMENT_TEMPLATE_VIEW_IF_CURRENT_REGULAR_CLIENT_CTM,

    DOCUMENT_TEMPLATE_ADD_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_TEMPLATE_MODIFY_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_TEMPLATE_ASSIGN_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_TEMPLATE_ASSIGN_IF_ASSOCIATED_ORGANIZATION,

    DOCUMENT_SIGNATURE_REQUEST_ADD_ALL_EXCEPT_OPTED_OUT,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_ASSOCIATED_ORGANIZATION,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_ASSOCIATED_COMMUNITY,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_CURRENT_RP_COMMUNITY_CTM,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_CURRENT_RP_CLIENT_CTM,
    DOCUMENT_SIGNATURE_REQUEST_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,

    // ============================================= Referrals =========================================================

    CLIENT_REFERRAL_ADD_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REFERRAL_ADD_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REFERRAL_ADD_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REFERRAL_ADD_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REFERRAL_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_REFERRAL_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    CLIENT_REFERRAL_ADD_IF_SELF_RECORD,
    B2B_REFERRAL_ADD_ALL,
    B2B_REFERRAL_ADD_IF_ASSOCIATED_ORGANIZATION,
    B2B_REFERRAL_ADD_IF_ASSOCIATED_COMMUNITY,
    B2B_REFERRAL_ADD_IF_CO_REGULAR_COMMUNITY_CTM,

    REFERRAL_VIEW_INBOUND_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_VIEW_INBOUND_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_VIEW_INBOUND_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_VIEW_INBOUND_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_VIEW_INBOUND_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,

    REFERRAL_PRE_ADMIT_INBOUND_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_PRE_ADMIT_INBOUND_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_PRE_ADMIT_INBOUND_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_PRE_ADMIT_INBOUND_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_PRE_ADMIT_INBOUND_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,

    REFERRAL_ACCEPT_INBOUND_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_ACCEPT_INBOUND_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_ACCEPT_INBOUND_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_ACCEPT_INBOUND_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_ACCEPT_INBOUND_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_ACCEPT_INBOUND_IF_FAX_SHARED,

    REFERRAL_REASSIGN_INBOUND_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_REASSIGN_INBOUND_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_REASSIGN_INBOUND_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_REASSIGN_INBOUND_IF_CO_REGULAR_COMMUNITY_CTM,

    REFERRAL_ADD_INFO_REQUEST_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_ADD_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_ADD_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_ADD_INFO_REQUEST_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_ADD_INFO_REQUEST_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,

    REFERRAL_VIEW_INBOUND_INFO_REQUEST_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_VIEW_INBOUND_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_VIEW_INBOUND_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_VIEW_INBOUND_INFO_REQUEST_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_VIEW_INBOUND_INFO_REQUEST_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,

    REFERRAL_DECLINE_INBOUND_ALL_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_DECLINE_INBOUND_IF_ASSOCIATED_ORGANIZATION,
    REFERRAL_DECLINE_INBOUND_IF_ASSOCIATED_COMMUNITY,
    REFERRAL_DECLINE_INBOUND_IF_CO_REGULAR_COMMUNITY_CTM,
    REFERRAL_DECLINE_INBOUND_IF_EXTERNAL_REFERRAL_REQUEST_EXCEPT_CLIENT_OPTED_OUT,
    REFERRAL_DECLINE_INBOUND_IF_FAX_SHARED,

    CLIENT_REFERRAL_VIEW_OUTBOUND_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REFERRAL_VIEW_OUTBOUND_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REFERRAL_VIEW_OUTBOUND_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REFERRAL_VIEW_OUTBOUND_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REFERRAL_VIEW_OUTBOUND_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_REFERRAL_VIEW_OUTBOUND_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    B2B_REFERRAL_VIEW_OUTBOUND_ALL,
    B2B_REFERRAL_VIEW_OUTBOUND_IF_ASSOCIATED_ORGANIZATION,
    B2B_REFERRAL_VIEW_OUTBOUND_IF_ASSOCIATED_COMMUNITY,
    B2B_REFERRAL_VIEW_OUTBOUND_IF_CO_REGULAR_COMMUNITY_CTM,

    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    B2B_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_ALL,
    B2B_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    B2B_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    B2B_REFERRAL_RESPOND_OUTBOUND_INFO_REQUEST_IF_CO_REGULAR_COMMUNITY_CTM,

    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_CURRENT_REGULAR_CLIENT_CTM,
    CLIENT_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    B2B_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_ALL,
    B2B_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_ORGANIZATION,
    B2B_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_ASSOCIATED_COMMUNITY,
    B2B_REFERRAL_VIEW_OUTBOUND_INFO_REQUEST_IF_CO_REGULAR_COMMUNITY_CTM,

    CLIENT_REFERRAL_CANCEL_OUTBOUND_ALL_EXCEPT_OPTED_OUT,
    CLIENT_REFERRAL_CANCEL_OUTBOUND_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_REFERRAL_CANCEL_OUTBOUND_IF_ASSOCIATED_COMMUNITY,
    CLIENT_REFERRAL_CANCEL_OUTBOUND_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    CLIENT_REFERRAL_CANCEL_OUTBOUND_IF_CURRENT_REGULAR_CLIENT_CTM,
    REFERRAL_CANCEL_OUTBOUND_IF_CREATED_BY_SELF,
    B2B_REFERRAL_CANCEL_OUTBOUND_ALL,
    B2B_REFERRAL_CANCEL_OUTBOUND_IF_ASSOCIATED_ORGANIZATION,
    B2B_REFERRAL_CANCEL_OUTBOUND_IF_ASSOCIATED_COMMUNITY,
    B2B_REFERRAL_CANCEL_OUTBOUND_IF_CO_REGULAR_COMMUNITY_CTM,

    // ============================================== Networks =========================================================

    PARTNER_NETWORK_VIEW_IF_ASSOCIATED_ORGANIZATION,
    PARTNER_NETWORK_VIEW_IF_ASSOCIATED_COMMUNITY,
    PARTNER_NETWORK_VIEW_IF_CO_REGULAR_COMMUNITY_CTM,
    PARTNER_NETWORK_VIEW_IF_CO_REGULAR_CLIENT_CTM,
    PARTNER_NETWORK_VIEW_IF_CLIENT_ADDED_BY_SELF,

    // ============================================== Labs =============================================================

    LAB_ADD_ALL_EXCEPT_OPTED_OUT,
    LAB_ADD_IF_ASSOCIATED_ORGANIZATION,
    LAB_ADD_IF_ASSOCIATED_COMMUNITY,
    LAB_ADD_IF_CO_REGULAR_COMMUNITY_CTM,
    LAB_ADD_IF_CURRENT_REGULAR_CLIENT_CTM,
    LAB_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    LAB_REVIEW_ALL_EXCEPT_OPTED_OUT_IF_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_REVIEW_IF_ASSOCIATED_ORGANIZATION_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_REVIEW_IF_ASSOCIATED_COMMUNITY_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_REVIEW_IF_CURRENT_REGULAR_COMMUNITY_CTM_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_REVIEW_IF_CURRENT_REGULAR_CLIENT_CTM_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_REVIEW_IF_OPTED_IN_CLIENT_ADDED_BY_SELF_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),

    LAB_VIEW_SENT_ALL_EXCEPT_OPTED_OUT,
    LAB_VIEW_SENT_IF_ASSOCIATED_ORGANIZATION,
    LAB_VIEW_SENT_IF_ASSOCIATED_COMMUNITY,
    LAB_VIEW_SENT_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    LAB_VIEW_SENT_IF_CURRENT_REGULAR_CLIENT_CTM,
    LAB_VIEW_SENT_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    LAB_PARTLY_VIEW_PENDING_ALL_EXCEPT_OPTED_OUT,
    LAB_PARTLY_VIEW_PENDING_IF_ASSOCIATED_ORGANIZATION,
    LAB_PARTLY_VIEW_PENDING_IF_ASSOCIATED_COMMUNITY,
    LAB_PARTLY_VIEW_PENDING_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    LAB_PARTLY_VIEW_PENDING_IF_CURRENT_REGULAR_CLIENT_CTM,
    LAB_PARTLY_VIEW_PENDING_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,

    LAB_VIEW_PENDING_ALL_EXCEPT_OPTED_OUT_IF_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_VIEW_PENDING_IF_ASSOCIATED_ORGANIZATION_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_VIEW_PENDING_IF_ASSOCIATED_COMMUNITY_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_VIEW_PENDING_IF_CURRENT_REGULAR_COMMUNITY_CTM_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_VIEW_PENDING_IF_CURRENT_REGULAR_CLIENT_CTM_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),
    LAB_VIEW_PENDING_IF_OPTED_IN_CLIENT_ADDED_BY_SELF_AND_COORDINATOR(PermissionPredicates.LABS_COORDINATOR),

    LAB_VIEW_REVIEWED_ALL_EXCEPT_OPTED_OUT,
    LAB_VIEW_REVIEWED_IF_ASSOCIATED_ORGANIZATION,
    LAB_VIEW_REVIEWED_IF_ASSOCIATED_COMMUNITY,
    LAB_VIEW_REVIEWED_IF_CURRENT_REGULAR_COMMUNITY_CTM,
    LAB_VIEW_REVIEWED_IF_CURRENT_REGULAR_CLIENT_CTM,
    LAB_VIEW_REVIEWED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    LAB_VIEW_REVIEWED_IF_SELF_RECORD,

    // ============================================== SDoH =============================================================
    SDOH_VIEW_IF_ASSOCIATED_ORGANIZATION,
    SDOH_DOWNLOAD_EXCEL_IF_ASSOCIATED_ORGANIZATION,
    SDOH_DOWNLOAD_ZIP_IF_ASSOCIATED_ORGANIZATION,

    SDOH_MARK_AS_SENT_IF_ASSOCIATED_ORGANIZATION,

    // ============================================== Incident Reports =================================================
    IR_MANAGE_OPTED_IN_IF_QA(PermissionPredicates.QA_INCIDENT_REPORTS),
    IR_MANAGE_IF_ASSOCIATED_ORGANIZATION_AND_QA(PermissionPredicates.QA_INCIDENT_REPORTS),
    IR_MANAGE_IF_ASSOCIATED_COMMUNITY_AND_QA(PermissionPredicates.QA_INCIDENT_REPORTS),

    // ============================================= Medications =========================================================

    MEDICATION_VIEW_MERGED_ALL_EXCEPT_OPTED_OUT,
    MEDICATION_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    MEDICATION_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    MEDICATION_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    MEDICATION_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    MEDICATION_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    MEDICATION_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    MEDICATION_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    MEDICATION_VIEW_MERGED_IF_SELF_RECORD,
    MEDICATION_VIEW_MERGED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    MEDICATION_ADD_ALL_EXCEPT_OPTED_OUT,
    MEDICATION_ADD_IF_ASSOCIATED_ORGANIZATION,
    MEDICATION_ADD_IF_ASSOCIATED_COMMUNITY,
    MEDICATION_ADD_IF_OPTED_IN_FROM_AFFILIATED_COMMUNITY,
    MEDICATION_ADD_IF_OPTED_IN_FROM_AFFILIATED_ORGANIZATION,
    MEDICATION_ADD_IF_CURRENT_RP_COMMUNITY_CTM,
    MEDICATION_ADD_IF_CURRENT_RP_CLIENT_CTM,
    MEDICATION_ADD_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    MEDICATION_ADD_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    MEDICATION_EDIT_ALL_EXCEPT_OPTED_OUT,
    MEDICATION_EDIT_IF_ASSOCIATED_ORGANIZATION,
    MEDICATION_EDIT_IF_ASSOCIATED_COMMUNITY,
    MEDICATION_EDIT_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    MEDICATION_EDIT_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    MEDICATION_EDIT_IF_CURRENT_RP_COMMUNITY_CTM,
    MEDICATION_EDIT_IF_CURRENT_RP_CLIENT_CTM,
    MEDICATION_EDIT_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    MEDICATION_EDIT_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    // ============================================= Allergies =========================================================

    ALLERGY_VIEW_MERGED_ALL_EXCEPT_OPTED_OUT,
    ALLERGY_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    ALLERGY_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    ALLERGY_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    ALLERGY_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    ALLERGY_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    ALLERGY_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    ALLERGY_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    ALLERGY_VIEW_MERGED_IF_SELF_RECORD,
    ALLERGY_VIEW_MERGED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    // ============================================= Problems =========================================================

    PROBLEM_VIEW_MERGED_ALL_EXCEPT_OPTED_OUT,
    PROBLEM_VIEW_MERGED_IF_ASSOCIATED_ORGANIZATION,
    PROBLEM_VIEW_MERGED_IF_ASSOCIATED_COMMUNITY,
    PROBLEM_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    PROBLEM_VIEW_MERGED_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    PROBLEM_VIEW_MERGED_IF_CURRENT_RP_COMMUNITY_CTM,
    PROBLEM_VIEW_MERGED_IF_CURRENT_RP_CLIENT_CTM,
    PROBLEM_VIEW_MERGED_IF_OPTED_IN_CLIENT_ADDED_BY_SELF,
    PROBLEM_VIEW_MERGED_IF_SELF_RECORD,
    PROBLEM_VIEW_MERGED_IF_ACCESSIBLE_REFERRAL_REQUEST,
    PROBLEM_VIEW_MERGED_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    // ============================================= Chat ==============================================================
    CHAT_ADD_CONTACT_ALL_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_ASSOCIATED_ORGANIZATION_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_FROM_PRIMARY_ORGANIZATION_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_FROM_AFFILIATED_ORGANIZATION_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_FROM_PRIMARY_COMMUNITY_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_FROM_AFFILIATED_COMMUNITY_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_CREATED_BY_SELF_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_SHARE_CURRENT_RP_CTM_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_SELF_RECORD_CURRENT_RP_CLIENT_CTM_EXCEPT_OPT_CLIENT_CONTACT,
    CHAT_ADD_CONTACT_IF_ACCESSIBLE_CLIENT_ASSOCIATED_CONTACT,

    // ============================================= Video call ==============================================================
    VIDEO_CALL_ADD_CONTACT_ALL_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_ASSOCIATED_ORGANIZATION_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_FROM_PRIMARY_ORGANIZATION_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_FROM_AFFILIATED_ORGANIZATION_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_FROM_PRIMARY_COMMUNITY_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_FROM_AFFILIATED_COMMUNITY_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_CREATED_BY_SELF_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_SHARE_CURRENT_RP_CTM_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_SELF_RECORD_CURRENT_RP_CLIENT_CTM_EXCEPT_OPT_OUT_CLIENT_CONTACT,
    VIDEO_CALL_ADD_CONTACT_IF_ACCESSIBLE_CLIENT_ASSOCIATED_CONTACT,

    VIDEO_CALL_VIEW_ASSOCIATED_CLIENT_HISTORY_IF_ASSOCIATED_ORGANIZATION,
    VIDEO_CALL_VIEW_ASSOCIATED_CLIENT_HISTORY_IF_FROM_AFFILIATED_ORGANIZATION,
    VIDEO_CALL_VIEW_ASSOCIATED_CLIENT_HISTORY_IF_ASSOCIATED_COMMUNITY,
    VIDEO_CALL_VIEW_ASSOCIATED_CLIENT_HISTORY_IF_FROM_AFFILIATED_COMMUNITY,
    VIDEO_CALL_VIEW_OWN_HISTORY,

    // ============================================= Release notes =====================================================
    VIEW_RELEASE_NOTES(PermissionPredicates.RELEASE_NOTES_ENABLED),

    // ============================================== User Manuals =====================================================
    VIEW_USER_MANUALS,

    // ============================================== Docutrack integration ============================================
    DOCUTRACK_CONFIGURE_ALL,
    DOCUTRACK_CONFIGURE_IF_ASSOCIATED_ORGANIZATION,
    DOCUTRACK_INTEGRATION_ALLOWED,

    // ============================================== Record search ====================================================
    CLIENT_RECORD_SEARCH_IF_ASSOCIATED_ORGANIZATION,

    // ================================================ Mobile app =====================================================
    MOBILE_APP_ACCESS,

    // ================================================ Paperless Healthcare ===========================================
    PAPERLESS_HEALTHCARE_ACCESS_IF_ENABLED(PermissionPredicates.PAPERLESS_HEALTHCARE),

    // =========================================== Client Location History =============================================
    CLIENT_LOCATION_HISTORY_VIEW_ALL_EXCEPT_OPTED_OUT,
    CLIENT_LOCATION_HISTORY_VIEW_IF_ASSOCIATED_ORGANIZATION,
    CLIENT_LOCATION_HISTORY_VIEW_IF_ASSOCIATED_COMMUNITY,
    CLIENT_LOCATION_HISTORY_VIEW_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    CLIENT_LOCATION_HISTORY_VIEW_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    CLIENT_LOCATION_HISTORY_VIEW_IF_CURRENT_RP_COMMUNITY_CTM,
    CLIENT_LOCATION_HISTORY_VIEW_IF_CURRENT_RP_CLIENT_CTM,
    CLIENT_LOCATION_HISTORY_VIEW_OPTED_IN_IF_ADDED_BY_SELF,
    CLIENT_LOCATION_HISTORY_VIEW_IF_SELF_RECORD,
    CLIENT_LOCATION_HISTORY_VIEW_IF_CLIENT_FOUND_IN_RECORD_SEARCH,

    CLIENT_LOCATION_HISTORY_ADD_ALL_EXCEPT_OPTED_OUT,
    CLIENT_LOCATION_HISTORY_ADD_IF_ASSOCIATED_ORGANIZATION,

    // =========================================== Appointments ========================================================
    APPOINTMENT_VIEW_LIST_ALL,
    APPOINTMENT_VIEW_LIST_IF_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_VIEW_LIST_IF_FROM_AFFILIATED_ORGANIZATION,
    APPOINTMENT_VIEW_LIST_IF_ASSOCIATED_COMMUNITY,
    APPOINTMENT_VIEW_LIST_IF_FROM_AFFILIATED_COMMUNITY,
    APPOINTMENT_VIEW_LIST_IF_CO_RP_COMMUNITY_CTM,
    APPOINTMENT_VIEW_LIST_IF_CO_RP_CLIENT_CTM,
    APPOINTMENT_VIEW_LIST_IF_SELF_CLIENT_RECORD,
    APPOINTMENT_VIEW_LIST_IF_ADDED_BY_SELF,

    APPOINTMENT_VIEW_ITEM_ALL_EXCEPT_OPTED_OUT,
    APPOINTMENT_VIEW_ITEM_IF_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_VIEW_ITEM_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    APPOINTMENT_VIEW_ITEM_IF_ASSOCIATED_COMMUNITY,
    APPOINTMENT_VIEW_ITEM_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    APPOINTMENT_VIEW_ITEM_IF_SELF_CLIENT_RECORD,
    APPOINTMENT_VIEW_ITEM_IF_ADDED_BY_SELF_AND_CLIENT_OPTED_IN,
    APPOINTMENT_VIEW_ITEM_IF_CURRENT_REGULAR_COMMUNITY_CTM_CREATED_BY_STAFF_FROM_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_VIEW_ITEM_IF_CURRENT_PRIMARY_COMMUNITY_CTM,
    APPOINTMENT_VIEW_ITEM_IF_CURRENT_REGULAR_CLIENT_CTM_CREATED_BY_STAFF_FROM_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_VIEW_ITEM_IF_CURRENT_PRIMARY_CLIENT_CTM,

    APPOINTMENT_ADD_ALL_EXCEPT_OPTED_OUT,
    APPOINTMENT_ADD_IF_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_ADD_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION,
    APPOINTMENT_ADD_IF_ASSOCIATED_COMMUNITY,
    APPOINTMENT_ADD_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY,
    APPOINTMENT_ADD_IF_CURRENT_RP_COMMUNITY_CTM,
    APPOINTMENT_ADD_IF_CURRENT_RP_CLIENT_CTM,
    APPOINTMENT_ADD_IF_SELF_CLIENT_RECORD,

    APPOINTMENT_EDIT_ALL_EXCEPT_OPTED_OUT,
    APPOINTMENT_EDIT_IF_ASSOCIATED_ORGANIZATION,
    APPOINTMENT_EDIT_OPTED_IN_IF_FROM_AFFILIATED_ORGANIZATION_CREATED_BY_STAFF_FROM_ASSOCIATED_ORGANIZATION_EXCEPT_PRS_PG,
    APPOINTMENT_EDIT_IF_ASSOCIATED_COMMUNITY,
    APPOINTMENT_EDIT_OPTED_IN_IF_FROM_AFFILIATED_COMMUNITY_CREATED_BY_STAFF_FROM_ASSOCIATED_COMMUNITY_EXCEPT_PRS_PG,
    APPOINTMENT_EDIT_IF_CURRENT_RP_COMMUNITY_CTM,
    APPOINTMENT_EDIT_IF_CURRENT_RP_CLIENT_CTM,
    APPOINTMENT_EDIT_IF_ADDED_BY_SELF_AND_CLIENT_OPTED_IN,

    // ================================================ Audit logs =====================================================
    AUDIT_LOG_VIEW_IF_ASSOCIATED_ORGANIZATION;

    private Predicate<Employee> permissionConfirmationPredicate;

    Permission() {
    }

    Permission(Predicate<Employee> permissionConfirmationPredicate) {
        this.permissionConfirmationPredicate = permissionConfirmationPredicate;
    }

    public Predicate<Employee> getPermissionConfirmationPredicate() {
        return permissionConfirmationPredicate;
    }

    public boolean hasPredicate() {
        return permissionConfirmationPredicate != null;
    }
}
