import { ACTION_TYPES } from 'lib/Constants'

const {
    CLEAR_NOTE_PAGE_NUMBER,
    CLEAR_NOTE_PAGE_NUMBER_ERROR,
    LOAD_NOTE_PAGE_NUMBER_REQUEST,
    LOAD_NOTE_PAGE_NUMBER_SUCCESS,
    LOAD_NOTE_PAGE_NUMBER_FAILURE
} = ACTION_TYPES

export default {
    CLEAR: CLEAR_NOTE_PAGE_NUMBER,
    CLEAR_ERROR: CLEAR_NOTE_PAGE_NUMBER_ERROR,
    LOAD_REQUEST: LOAD_NOTE_PAGE_NUMBER_REQUEST,
    LOAD_SUCCESS: LOAD_NOTE_PAGE_NUMBER_SUCCESS,
    LOAD_FAILURE: LOAD_NOTE_PAGE_NUMBER_FAILURE
}