package com.scnsoft.eldermark.entity;

public enum AuditLogAction {
    LOG_IN,
    PATIENT_DISCOVERY,
    QUERY_FOR_DOCUMENTS,
    FILTER_DOCUMENTS,
    DOCUMENT_VIEW,
    DOCUMENT_DOWNLOAD,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    CCD_GENERATE_AND_VIEW,
    CCD_GENERATE_AND_DOWNLOAD,
    FACESHEET_GENERATE_AND_VIEW,
    FACESHEET_GENERATE_AND_DOWNLOAD,
    LOG_OUT
}
