package com.scnsoft.eldermark.entity;


public enum RoleCode {
    ROLE_ELDERMARK_USER("ROLE_ELDERMARK_USER"),
    ROLE_MANAGER("ROLE_MANAGER"),
    ROLE_DIRECT_MANAGER("ROLE_DIRECT_MANAGER"),
    ROLE_SUPER_MANAGER("ROLE_SUPER_MANAGER"),
    ROLE_SCAN_SOL_MANAGER("ROLE_SCAN_SOL_MANAGER"),
    ROLE_CLOUD_STORAGE_USER("ROLE_CLOUD_STORAGE_USER"),
    ROLE_PARTNER_USER("ROLE_PARTNER_USER"),
    ROLE_CLOUD_STORAGE_CATEGORY_MANAGER("ROLE_CLOUD_STORAGE_CATEGORY_MANAGER"),
	ROLE_CLOUD_STORAGE_SUPER_ADMIN("ROLE_CLOUD_STORAGE_SUPER_ADMIN"),
    ROLE_SIMPLY_CONNECT_ADMINISTRATOR("ROLE_SIMPLY_CONNECT_ADMINISTRATOR"),
    ROLE_SIMPLY_CONNECT_BEHAVIORAL_HEALTH("ROLE_SIMPLY_CONNECT_BEHAVIORAL_HEALTH"),
    ROLE_SIMPLY_CONNECT_CARE_COORDINATOR("ROLE_SIMPLY_CONNECT_CARE_COORDINATOR"),
    ROLE_SIMPLY_CONNECT_CASE_MANAGER("ROLE_SIMPLY_CONNECT_CASE_MANAGER"),
    ROLE_SIMPLY_CONNECT_COMMUNITY_ADMINISTRATOR("ROLE_SIMPLY_CONNECT_COMMUNITY_ADMINISTRATOR"),
    ROLE_SIMPLY_CONNECT_COMMUNITY_MEMBERS("ROLE_SIMPLY_CONNECT_COMMUNITY_MEMBERS"),
    ROLE_SIMPLY_CONNECT_PRIMARY_PHYSICIAN("ROLE_SIMPLY_CONNECT_PRIMARY_PHYSICIAN"),
    ROLE_SIMPLY_CONNECT_SERVICE_PROVIDERS("ROLE_SIMPLY_CONNECT_SERVICE_PROVIDERS"),
    ROLE_SIMPLY_CONNECT_SUPER_ADMINISTRATOR("ROLE_SIMPLY_CONNECT_SUPER_ADMINISTRATOR");
	
    private String name;

    RoleCode(String name){
        this.name = name;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return name;
    }

    public static RoleCode getByName(final String name){
        for (RoleCode c: RoleCode.values()){
            if (c.getName().equals(name)){
                return c;
            }
        }
        return null;
    }
}
