import { SYSTEM_ROLES } from "lib/Constants";

export let PROFESSIONAL_SYSTEM_ROLES = [
  // SYSTEM_ROLES.CASE_MANAGER, // change care manager role
  SYSTEM_ROLES.CARE_COORDINATOR,
  SYSTEM_ROLES.COMMUNITY_MEMBERS,
  SYSTEM_ROLES.PRIMARY_PHYSICIAN,
  SYSTEM_ROLES.BEHAVIORAL_HEALTH,
  SYSTEM_ROLES.SERVICE_PROVIDER,
  SYSTEM_ROLES.NURSE,
  SYSTEM_ROLES.TELE_HEALTH_NURSE,
];
