CREATE NONCLUSTERED INDEX [IX_resident_id_opt_out] ON [dbo].[resident_enc]
(
	[id] ASC,
	[opt_out] ASC
)
INCLUDE ( 	[facility_id]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
