SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
UPDATE [dbo].[Assessment]
   SET [json_content] = N'{"pages":[{"name":"page1","elements":[{"type":"radiogroup","name":"question1","title":"Hospitalizations in the last 2 years?","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question2","isRequired":true,"customdatepicker":true,"visibleIf":"{question1} = \"item1\"","title":"Date"},{"type":"text","name":"question3","visibleIf":"{question1} = \"item1\"","title":"Hospital"},{"type":"text","name":"question4","visibleIf":"{question1} = \"item1\"","title":"Diagnosis"},{"type":"text","name":"question5","visibleIf":"{question1} = \"item1\"","title":"LOS"},{"type":"radiogroup","name":"question6","title":"Emergency visits not resulting in hospitalizations in the last 2 years?","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question7","isRequired":true,"customdatepicker":true,"visibleIf":"{question6} = \"item1\"","title":"Date"},{"type":"text","name":"question8","visibleIf":"{question6} = \"item1\"","title":"Hospital"},{"type":"text","name":"question9","visibleIf":"{question6} = \"item1\"","title":"Reason for ER Visit"},{"type":"text","name":"question10","visibleIf":"{question6} = \"item1\"","title":"Diagnosis"},{"type":"radiogroup","name":"question11","title":"Outpatient Procedures","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question12","isRequired":true,"customdatepicker":true,"visibleIf":"{question11} = \"item1\"","title":"Date"},{"type":"text","name":"question13","visibleIf":"{question11} = \"item1\"","title":"Hospital or Other Site"},{"type":"text","name":"question14","visibleIf":"{question11} = \"item1\"","title":"Diagnosis"},{"type":"text","name":"question15","visibleIf":"{question11} = \"item1\"","title":"Procedure"},{"type":"radiogroup","name":"question16","title":"PCP Visits","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question17","isRequired":true,"customdatepicker":true,"visibleIf":"{question16} = \"item1\"","title":"Date"},{"type":"text","name":"question18","visibleIf":"{question16} = \"item1\"","title":"Diagnoses"},{"type":"radiogroup","name":"question19","title":"Ancillary Utilization","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question20","isRequired":true,"customdatepicker":true,"visibleIf":"{question19} = \"item1\"","title":"Date"},{"type":"text","name":"question21","visibleIf":"{question19} = \"item1\"","title":"Provider"},{"type":"text","name":"question22","visibleIf":"{question19} = \"item1\"","title":"Diagnoses"},{"type":"text","name":"question23","visibleIf":"{question19} = \"item1\"","title":"DME"}],"title":"Utilization"}]}'
 WHERE id=3
GO

SET ANSI_PADDING OFF
GO
