SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
UPDATE [dbo].[Assessment]
   SET [json_content] = N'{"pages":[{"name":"page1","elements":[{"type":"radiogroup","name":"question1","title":"1. Hospitalizations in the last 2 years?","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question2","customdatepicker":true,"visibleIf":"{question1} = \"item1\"","title":"1.1. Date","isRequired":true},{"type":"text","name":"question3","visibleIf":"{question1} = \"item1\"","title":"1.2. Hospital"},{"type":"text","name":"question4","visibleIf":"{question1} = \"item1\"","title":"1.3. Diagnosis"},{"type":"text","name":"question5","visibleIf":"{question1} = \"item1\"","title":"1.4. LOS"},{"type":"radiogroup","name":"question6","title":"2. Emergency visits not resulting in hospitalizations in the last 2 years?","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question7","customdatepicker":true,"visibleIf":"{question6} = \"item1\"","title":"2.1. Date","isRequired":true},{"type":"text","name":"question8","visibleIf":"{question6} = \"item1\"","title":"2.2. Hospital"},{"type":"text","name":"question9","visibleIf":"{question6} = \"item1\"","title":"2.3. Reason for ER Visit"},{"type":"text","name":"question10","visibleIf":"{question6} = \"item1\"","title":"2.4. Diagnosis"},{"type":"radiogroup","name":"question11","title":"3. Outpatient Procedures","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question12","customdatepicker":true,"visibleIf":"{question11} = \"item1\"","title":"3.1. Date","isRequired":true},{"type":"text","name":"question13","visibleIf":"{question11} = \"item1\"","title":"3.2. Hospital or Other Site"},{"type":"text","name":"question14","visibleIf":"{question11} = \"item1\"","title":"3.3. Diagnosis"},{"type":"text","name":"question15","visibleIf":"{question11} = \"item1\"","title":"3.4. Procedure"},{"type":"radiogroup","name":"question16","title":"4. PCP Visits","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question17","customdatepicker":true,"visibleIf":"{question16} = \"item1\"","title":"4.1. Date","isRequired":true},{"type":"text","name":"question18","visibleIf":"{question16} = \"item1\"","title":"4.2. Diagnoses"},{"type":"radiogroup","name":"question19","title":"5. Ancillary Utilization","isRequired":true,"choices":[{"value":"item1","text":"Yes"},{"value":"item2","text":"No"}]},{"type":"text","name":"question20","customdatepicker":true,"visibleIf":"{question19} = \"item1\"","title":"5.1. Date","isRequired":true},{"type":"text","name":"question21","visibleIf":"{question19} = \"item1\"","title":"5.2. Provider"},{"type":"text","name":"question22","visibleIf":"{question19} = \"item1\"","title":"5.3. Diagnoses"},{"type":"text","name":"question23","visibleIf":"{question19} = \"item1\"","title":"5.4. DME"}],"title":"Utilization"}],"showQuestionNumbers":"off"}'
 WHERE id=3
GO

SET ANSI_PADDING OFF
GO
