SET XACT_ABORT ON
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Diagnosis](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[legacy_id] [varchar](255) NOT NULL,
	[code] [varchar](255) NULL,
	[inactive] [bit] NULL,
	[name] [varchar](255) NULL,
	[database_id] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Diagnosis]  WITH CHECK ADD  CONSTRAINT [FK_e4r52lujcopcg8097y1s4d352] FOREIGN KEY([database_id])
REFERENCES [dbo].[SourceDatabase] ([id])
GO

ALTER TABLE [dbo].[Diagnosis] CHECK CONSTRAINT [FK_e4r52lujcopcg8097y1s4d352]
GO
