INSERT INTO [dbo].[Role]
           ([name])
     VALUES
           ('ROLE_SIMPLY_CONNECT_ADMINISTRATOR'),
		   ('ROLE_SIMPLY_CONNECT_BEHAVIORAL_HEALTH'),
		   ('ROLE_SIMPLY_CONNECT_CARE_COORDINATOR'),
		   ('ROLE_SIMPLY_CONNECT_CASE_MANAGER'),
		   ('ROLE_SIMPLY_CONNECT_COMMUNITY_ADMINISTRATOR'),
		   ('ROLE_SIMPLY_CONNECT_COMMUNITY_MEMBERS'),
		   ('ROLE_SIMPLY_CONNECT_PRIMARY_PHYSICIAN'),
		   ('ROLE_SIMPLY_CONNECT_SERVICE_PROVIDERS'),
		   ('ROLE_SIMPLY_CONNECT_SUPER_ADMINISTRATOR');

GO