define([path('app/lib/Constants')], function (constants) {
    var types = constants.actionTypes;

    return {
        CLEAN: types.CLEAN_INCIDENT_LEVEL_REPORTING_SETTINGS,
        CLEAN_ERROR: types.CLEAN_INCIDENT_LEVEL_REPORTING_SETTINGS_ERROR,
        LOAD_REQUEST: types.LOAD_INCIDENT_LEVEL_REPORTING_SETTINGS_REQUEST,
        LOAD_SUCCESS: types.LOAD_INCIDENT_LEVEL_REPORTING_SETTINGS_SUCCESS,
        LOAD_FAILURE: types.LOAD_INCIDENT_LEVEL_REPORTING_SETTINGS_FAILURE
    }
});