import {
    APPOINTMENT_TYPES
} from 'lib/Constants'

import {
    EVENT_COLORS,
} from 'components/Calendar/Constants'

export const APPOINTMENT_TYPE_EVENT_COLORS = {
    [APPOINTMENT_TYPES.CHECK_UP]: EVENT_COLORS.YELLOW,
    [APPOINTMENT_TYPES.EMERGENCY]: EVENT_COLORS.RED,
    [APPOINTMENT_TYPES.FOLLOW_UP]: EVENT_COLORS.BLUE,
    [APPOINTMENT_TYPES.POST_OP]: EVENT_COLORS.DARK_BLUE,
    [APPOINTMENT_TYPES.ROUTINE]: EVENT_COLORS.GREEN,
    [APPOINTMENT_TYPES.OTHER]: EVENT_COLORS.VIOLET,
}