package com.scnsoft.eldermark.beans.projection;

public interface DocumentSignatureTemplateAuditLogDetailsAware extends DocumentSignatureTemplateSecurityFieldsAware, IsManuallyCreatedAware,TitleAware {
}
