package com.scnsoft.eldermark.framework;

public enum DataSyncStep {
    LOAD_ID_UPPER_BOUND,
    SET_STATUS_IN_PROGRESS,
    LOAD_SOURCE_DATA,
    RESOLVE_FOREIGN_KEYS,
    FIND_NEW_AND_EXISTING_ENTITIES,
    INSERT_ENTITIES,
    UPDATE_ENTITIES,
    APPEND_DATA_SYNC_LOG,
    SET_STATUS_SYNCHRONIZED,
    SYNC_DELETED
}
