import { useAuthUser } from "hooks/common/redux";

import { SYSTEM_ROLES } from "lib/Constants";

const {
  ADMINISTRATOR,
  ORGANIZATION_ADMIN,
  VENDOR,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  CLINICIAN,
  PHARMACIST_VENDOR,
  NAVI_GUIDE,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  COMMUNITY_ADMINISTRATOR,
  NURSE,
  CARE_COORDINATOR,
  CASE_MANAGER,
  COMMUNITY_PROVIDER,
} = SYSTEM_ROLES;

const ALLOWED_ROLES = [
  ADMINISTRATOR,
  ORGANIZATION_ADMIN,
  VENDOR,
  ASSOCIATION,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  CLINICIAN,
  PHARMACIST_VENDOR,
  NAVI_GUIDE,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  COMMUNITY_ADMINISTRATOR,
  NURSE,
  CARE_COORDINATOR,
  CASE_MANAGER,
  COMMUNITY_PROVIDER,
  NON_CLINICAL_STAFF,
];

export default function useCanLoginToNotify() {
  const user = useAuthUser();
  return ALLOWED_ROLES.includes(user?.roleName);
}
