SET XACT_ABORT ON;

ALTER TABLE [dbo].[RXNSAT] DROP COLUMN LUI;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN SUI;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN RXAUI;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN STYPE;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN ATUI;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN SATUI;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN SUPPRESS;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN CVF;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN RXCUI;

DELETE FROM [dbo].[RXNSAT] WHERE NOT (SAB='RXNORM' AND ATN='NDC');

ALTER TABLE [dbo].[RXNSAT] DROP COLUMN ATN;
ALTER TABLE [dbo].[RXNSAT] DROP COLUMN SAB;
