import { SYSTEM_ROLES } from "lib/Constants";

export const {
  CASE_MANAGER,
  CARE_COORDINATOR,
  PARENT_GUARDIAN,
  PERSON_RECEIVING_SERVICES,
  CLIENT_POA,
  PRIMARY_PHYSICIAN,
  BEHAVIORAL_HEALTH,
  COMMUNITY_MEMBERS,
  SERVICE_PROVIDER,
  ADMINISTRATOR,
  SUPER_ADMINISTRATOR,
  ORGANIZATION_ADMIN,
  VENDOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  CLINICIAN,
  PHARMACIST_VENDOR,
  NAVI_GUIDE,
  QUALITY_ASSURANCE,
  EXTERNAL_PROVIDER,
  COMMUNITY_ADMINISTRATOR,
  PHARMACIST,
  PHARMACY_TECHNICIAN,
  NURSE,
  HOME_CARE_ASSISTANT,
  CONTENT_CREATOR,
  TELE_HEALTH_NURSE,
  VENDOR_ADMIN,
  VENDOR_CONCIERGE,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
  ROLE_COMMUNITY_DOCTOR,
} = SYSTEM_ROLES;

const PROFESSIONALS_CARE_MANAGEMENT = [CASE_MANAGER, CARE_COORDINATOR, COMMUNITY_MEMBERS];

const PROFESSIONALS_PRIMARY_PHYSICIAN = [PRIMARY_PHYSICIAN];

const PROFESSIONALS_OTHER = [BEHAVIORAL_HEALTH, SERVICE_PROVIDER, NURSE, TELE_HEALTH_NURSE];

const PHARMACY = [PHARMACIST, PHARMACY_TECHNICIAN];

const NON_PROFESSIONALS = [PARENT_GUARDIAN];

export const GROUPS = {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
};
