//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.22 at 05:31:09 PM MSK 
//


package com.scnsoft.eldermark.event.xml.schema;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Organization" type="{}Organization"/&gt;
 *         &lt;element name="Community" type="{}Community"/&gt;
 *         &lt;element name="Patient" type="{}Patient"/&gt;
 *         &lt;element name="FormAuthor" type="{}FormAuthor"/&gt;
 *         &lt;element name="Manager" type="{}Manager" minOccurs="0"/&gt;
 *         &lt;element name="RN" type="{}RN" minOccurs="0"/&gt;
 *         &lt;element name="EventDetails" type="{}EventDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "organization",
    "community",
    "patient",
    "formAuthor",
    "manager",
    "rn",
    "eventDetails"
})
public class Event {

    @XmlElement(name = "Organization", required = true)
    protected Organization organization;
    @XmlElement(name = "Community", required = true)
    protected Community community;
    @XmlElement(name = "Patient", required = true)
    protected Patient patient;
    @XmlElement(name = "FormAuthor", required = true)
    protected FormAuthor formAuthor;
    @XmlElement(name = "Manager")
    protected Manager manager;
    @XmlElement(name = "RN")
    protected RN rn;
    @XmlElement(name = "EventDetails", required = true)
    protected EventDetails eventDetails;

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the community property.
     * 
     * @return
     *     possible object is
     *     {@link Community }
     *     
     */
    public Community getCommunity() {
        return community;
    }

    /**
     * Sets the value of the community property.
     * 
     * @param value
     *     allowed object is
     *     {@link Community }
     *     
     */
    public void setCommunity(Community value) {
        this.community = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

    /**
     * Gets the value of the formAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link FormAuthor }
     *     
     */
    public FormAuthor getFormAuthor() {
        return formAuthor;
    }

    /**
     * Sets the value of the formAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormAuthor }
     *     
     */
    public void setFormAuthor(FormAuthor value) {
        this.formAuthor = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link Manager }
     *     
     */
    public Manager getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manager }
     *     
     */
    public void setManager(Manager value) {
        this.manager = value;
    }

    /**
     * Gets the value of the rn property.
     * 
     * @return
     *     possible object is
     *     {@link RN }
     *     
     */
    public RN getRN() {
        return rn;
    }

    /**
     * Sets the value of the rn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RN }
     *     
     */
    public void setRN(RN value) {
        this.rn = value;
    }

    /**
     * Gets the value of the eventDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EventDetails }
     *     
     */
    public EventDetails getEventDetails() {
        return eventDetails;
    }

    /**
     * Sets the value of the eventDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDetails }
     *     
     */
    public void setEventDetails(EventDetails value) {
        this.eventDetails = value;
    }

}
