//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 11:32:16 AM MSK 
//


package com.scnsoft.eldermark.framework.connector4d.xml4Dconnector.schema;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authentication",
    "sqlrequest"
})
@XmlRootElement(name = "communication")
public class CommunicationRequest {

    @XmlElement(required = true)
    protected Authentication authentication;
    @XmlElement(required = true)
    protected Sqlrequest sqlrequest;
    @XmlAttribute(name = "requestid")
    protected Long requestid;
    @XmlAttribute(name = "version")
    protected Integer version;


    public Authentication getAuthentication() {
        return authentication;
    }

    public void setAuthentication(Authentication value) {
        this.authentication = value;
    }

    public Sqlrequest getSqlrequest() {
        return sqlrequest;
    }

    public void setSqlrequest(Sqlrequest value) {
        this.sqlrequest = value;
    }

    public Long getRequestid() {
        return requestid;
    }

    public void setRequestid(Long value) {
        this.requestid = value;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer value) {
        this.version = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Authentication {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "session_id")
        protected Long sessionId;
        @XmlAttribute(name = "session_key")
        protected String sessionKey;
        @XmlAttribute(name = "userlogin_name")
        protected String userloginName;
        @XmlAttribute(name = "userlogin_password")
        protected String userloginPassword;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public Long getSessionId() {
            return sessionId;
        }

        public void setSessionId(Long value) {
            this.sessionId = value;
        }

        public String getSessionKey() {
            return sessionKey;
        }

        public void setSessionKey(String value) {
            this.sessionKey = value;
        }

        public String getUserloginName() {
            return userloginName;
        }

        public void setUserloginName(String value) {
            this.userloginName = value;
        }

        public String getUserloginPassword() {
            return userloginPassword;
        }

        public void setUserloginPassword(String value) {
            this.userloginPassword = value;
        }
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sql",
        "returnvarlist"
    })
    public static class Sqlrequest {

        @XmlElement(required = true)
        protected Sql sql;
        @XmlElement(required = true)
        protected Returnvarlist returnvarlist;
        @XmlAttribute(name = "requestid")
        protected Long requestid;
        @XmlAttribute(name = "rollbackifproblems")
        protected Integer rollbackifproblems;
        @XmlAttribute(name = "version")
        protected Integer version;

        public Sql getSql() {
            return sql;
        }

        public void setSql(Sql value) {
            this.sql = value;
        }

        public Returnvarlist getReturnvarlist() {
            return returnvarlist;
        }

        public void setReturnvarlist(Returnvarlist value) {
            this.returnvarlist = value;
        }

        public Long getRequestid() {
            return requestid;
        }

        public void setRequestid(Long value) {
            this.requestid = value;
        }

        public Integer getRollbackifproblems() {
            if (rollbackifproblems == null) {
                return 0;
            } else {
                return rollbackifproblems;
            }
        }

        public void setRollbackifproblems(Integer value) {
            this.rollbackifproblems = value;
        }

        public Integer getVersion() {
            if (version == null) {
                return 5;
            } else {
                return version;
            }
        }

        public void setVersion(Integer value) {
            this.version = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "var"
        })
        public static class Returnvarlist {

            protected List<Var> var;

            public List<Var> getVar() {
                if (var == null) {
                    var = new ArrayList<Var>();
                }
                return this.var;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Var {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "num")
                protected Integer num;
                @XmlAttribute(name = "type")
                protected String type;

                public String getValue() {
                    return value;
                }

                public void setValue(String value) {
                    this.value = value;
                }

                public String getName() {
                    return name;
                }

                public void setName(String value) {
                    this.name = value;
                }

                public Integer getNum() {
                    return num;
                }

                public void setNum(Integer value) {
                    this.num = value;
                }

                public String getType() {
                    return type;
                }

                public void setType(String value) {
                    this.type = value;
                }

            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Sql {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "encoding")
            protected String encoding;

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getEncoding() {
                return encoding;
            }

            public void setEncoding(String value) {
                this.encoding = value;
            }

        }

    }

}
