//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 11:43:41 AM MSK 
//


package com.scnsoft.eldermark.framework.connector4d.xml4Dconnector.schema;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authentication",
    "sqlrequest"
})
@XmlRootElement(name = "communication")
public class CommunicationResponse {

    @XmlElement(required = true)
    protected Authentication authentication;
    @XmlElement(required = true)
    protected Sqlrequest sqlrequest;
    @XmlAttribute(name = "requestid")
    protected Integer requestid;
    @XmlAttribute(name = "version")
    protected Byte version;

    public Authentication getAuthentication() {
        return authentication;
    }

    public void setAuthentication(Authentication value) {
        this.authentication = value;
    }

    public Sqlrequest getSqlrequest() {
        return sqlrequest;
    }

    public void setSqlrequest(Sqlrequest value) {
        this.sqlrequest = value;
    }

    public Integer getRequestid() {
        return requestid;
    }

    public void setRequestid(Integer value) {
        this.requestid = value;
    }

    public Byte getVersion() {
        return version;
    }

    public void setVersion(Byte value) {
        this.version = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Authentication {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "employee_firstname")
        protected String employeeFirstname;
        @XmlAttribute(name = "employee_id")
        protected String employeeId;
        @XmlAttribute(name = "employee_lastname")
        protected String employeeLastname;
        @XmlAttribute(name = "sm_build_number")
        protected Short smBuildNumber;
        @XmlAttribute(name = "success")
        protected Byte success;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public String getEmployeeFirstname() {
            return employeeFirstname;
        }

        public void setEmployeeFirstname(String value) {
            this.employeeFirstname = value;
        }

        public String getEmployeeId() {
            return employeeId;
        }

        public void setEmployeeId(String value) {
            this.employeeId = value;
        }

        public String getEmployeeLastname() {
            return employeeLastname;
        }

        public void setEmployeeLastname(String value) {
            this.employeeLastname = value;
        }

        public Short getSmBuildNumber() {
            return smBuildNumber;
        }

        public void setSmBuildNumber(Short value) {
            this.smBuildNumber = value;
        }

        public Byte getSuccess() {
            return success;
        }

        public void setSuccess(Byte value) {
            this.success = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnvarlist"
    })
    public static class Sqlrequest {

        @XmlElement(required = true)
        protected Returnvarlist returnvarlist;
        @XmlAttribute(name = "errornum")
        protected Byte errornum;
        @XmlAttribute(name = "errortext")
        protected String errortext;
        @XmlAttribute(name = "recipient_AppType")
        protected String recipientAppType;
        @XmlAttribute(name = "requestid")
        protected Byte requestid;
        @XmlAttribute(name = "version")
        protected Byte version;

        public Returnvarlist getReturnvarlist() {
            return returnvarlist;
        }

        public void setReturnvarlist(Returnvarlist value) {
            this.returnvarlist = value;
        }

        public Byte getErrornum() {
            return errornum;
        }

        public void setErrornum(Byte value) {
            this.errornum = value;
        }

        public String getErrortext() {
            return errortext;
        }

        public void setErrortext(String value) {
            this.errortext = value;
        }

        public String getRecipientAppType() {
            return recipientAppType;
        }

        public void setRecipientAppType(String value) {
            this.recipientAppType = value;
        }

        public Byte getRequestid() {
            return requestid;
        }

        public void setRequestid(Byte value) {
            this.requestid = value;
        }

        public Byte getVersion() {
            return version;
        }

        public void setVersion(Byte value) {
            this.version = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "column"
        })
        public static class Returnvarlist {

            protected List<Column> column;
            @XmlAttribute(name = "arraysize")
            protected Byte arraysize;

            public List<Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Column>();
                }
                return this.column;
            }

            public Byte getArraysize() {
                return arraysize;
            }

            public void setArraysize(Byte value) {
                this.arraysize = value;
            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Column {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "encoding")
                protected String encoding;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "num")
                protected Integer num;
                @XmlAttribute(name = "type")
                protected String type;

                public String getValue() {
                    return value;
                }

                public void setValue(String value) {
                    this.value = value;
                }

                public String getEncoding() {
                    return encoding;
                }

                public void setEncoding(String value) {
                    this.encoding = value;
                }

                public String getName() {
                    return name;
                }

                public void setName(String value) {
                    this.name = value;
                }

                public Integer getNum() {
                    return num;
                }

                public void setNum(Integer value) {
                    this.num = value;
                }

                public String getType() {
                    return type;
                }

                public void setType(String value) {
                    this.type = value;
                }
            }
        }
    }
}
