package com.scnsoft.eldermark;

public class Constants {
    public static final String[] EXCLUDED_TABLES = {
        "CcdCode",
        "Document",
        //"Document_SourceDatabase",
        "DataSyncLogType",
        "DataSyncObjectStatus",
        "DataSyncIteration",
        //"DataSyncLog",
        //"DataSyncStats",
        "SourceDatabaseAddressAndContacts",
        "database_org_count",
        "DataSyncDataLog",
        "schema_version",
        "SourceDatabase",
        "AuditLog",
        "AuditLog_Documents",
        "AuditLog_Residents",
        "Role",
        "Employee_Role",
        "Calendar",
        "DirectConfiguration",
        "State",
        "EventType",
        "NotificationPreferences",
        "CareTeamRole",
        "CareTeamMember",
        "CareTeamMemberNotificationPreferences",
        "OrganizationCareTeamMember",
        "ResidentCareTeamMember",
        "EventAddress",
        "EventRN",
        "EventManager",
        "EventAuthor",
        "EventTreatingPhysician",
        "EventTreatingHospital",
        "Event",
        "EventNotification",
        "EventType_CareTeamRole_Xref",
        "EventsProvider",
        "EmployeeRequest",
        "EventsLog",
        "InterfaxConfiguration"
    };
}
