package com.scnsoft.eldermark.services.consol.templates.sections;

import com.scnsoft.eldermark.entity.*;
import com.scnsoft.eldermark.services.cda.util.CcdUtils;
import com.scnsoft.eldermark.services.cda.templates.RequiredTemplateFactory;
import com.scnsoft.eldermark.services.cda.templates.SectionFactory;
import org.apache.commons.text.StringEscapeUtils;
import org.eclipse.mdht.uml.cda.*;
import org.eclipse.mdht.uml.hl7.datatypes.*;
import org.eclipse.mdht.uml.hl7.vocab.*;
import org.openhealthtools.mdht.uml.cda.consol.ConsolFactory;
import org.openhealthtools.mdht.uml.cda.consol.ResultsSection;
import org.springframework.stereotype.Component;
import org.springframework.util.CollectionUtils;

import java.math.BigDecimal;
import java.util.Collection;

/**
 * <h1>Results</h1>
 * “This section contains the results of observations generated by laboratories, imaging procedures,
 * and other procedures ... The section may contain all results for the period of time being summarized,
 * but should include notable results such as abnormal values or relevant trends.” [CCD 3.13].
 * <p>
 * Laboratory results are typically generated by laboratories providing analytic services in areas such as
 * chemistry, hematology, serology, histology, cytology, anatomic pathology, microbiology, and/or virology.
 * These observations are based on analysis of specimens obtained from the patient and submitted to the laboratory.
 * Imaging results are typically generated by a clinician reviewing the output of an imaging procedure,
 * such as where a cardiologist reports the left ventricular ejection fraction based on the review of a
 * cardiac echocardiogram.
 * <p>
 * Procedure results are typically generated by a clinician to provide more granular information about
 * component observations made during a procedure, such as where a gastroenterologist reports the size
 * of a polyp observed during a colonoscopy.
 *
 * @see Result
 * @see ResultObservation
 * @see CcdCode
 * @see Resident
 */
@Component("consol.ResultsFactory")
public class ResultsFactory extends RequiredTemplateFactory implements SectionFactory<ResultsSection, Result> {

    private static final String LEGACY_TABLE = "Results_NWHIN";
    private static final String TEMPLATE_ID_STR = "2.16.840.1.113883.10.20.22.2.3.1";

    @Override
    public ResultsSection buildTemplateInstance(Collection<Result> results) {
        final ResultsSection section = ConsolFactory.eINSTANCE.createResultsSection();
        section.getTemplateIds().add(DatatypesFactory.eINSTANCE.createII(TEMPLATE_ID_STR));

        CE sectionCode = CcdUtils.createCE("30954-2", "RESULTS", CodeSystem.LOINC);
        section.setCode(sectionCode);

        ST title = DatatypesFactory.eINSTANCE.createST();
        title.addText("Results");
        section.setTitle(title);

        section.createStrucDocText(buildSectionText(results));

        if (CollectionUtils.isEmpty(results)) {
            Entry entry = CDAFactory.eINSTANCE.createEntry();
            entry.setOrganizer(buildNullResultOrganizer());
            section.getEntries().add(entry);

            return section;
        }

        for (Result result : results) {
            Entry entry = CDAFactory.eINSTANCE.createEntry();
            entry.setOrganizer(buildResultOrganizer(result));
            section.getEntries().add(entry);
        }

        return section;
    }

    public Organizer buildResultOrganizer(Result result) {
        Organizer organizer = CDAFactory.eINSTANCE.createOrganizer();

        // (CONF-7121, CONF-7165) Attribute 'classCode' must appear on element 'organizer'
        // (CONF-7165) The 'classCode' attribute of the 'organizer' element can take one of two values:
        // * “BATTERY” – Used when the contents of the organizer are a group of related clinical acts (typically, observations)
        //               in a flat list, as would be the case in a battery of tests.
        // * “CLUSTER” – Used for more complex organizer constructs with nested organizer
        if (result.getClassCode() != null) {
            organizer.setClassCode(x_ActClassDocumentEntryOrganizer.valueOf(result.getClassCode()));
        } else {
            organizer.setClassCode(x_ActClassDocumentEntryOrganizer.BATTERY);
        }

        organizer.setMoodCode(ActMood.EVN);

        II templateId = DatatypesFactory.eINSTANCE.createII();
        templateId.setRoot("2.16.840.1.113883.10.20.22.4.1");
        organizer.getTemplateIds().add(templateId);

        organizer.getIds().add(CcdUtils.getId(result.getId()));

        CE code = CcdUtils.createCE(result.getCode());
        organizer.setCode(code);

        CS statusCode = DatatypesFactory.eINSTANCE.createCS();
        if (result.getStatusCode() != null) {
            statusCode.setCode(result.getStatusCode());
        } else {
            statusCode.setNullFlavor(NullFlavor.NI);
        }
        organizer.setStatusCode(statusCode);

        if (!CollectionUtils.isEmpty(result.getObservations())) {
            for (ResultObservation resultObservation : result.getObservations()) {
                Component4 component4 = CDAFactory.eINSTANCE.createComponent4();
                component4.setObservation(buildResultObservation(resultObservation));
                organizer.getComponents().add(component4);
            }
        } else {
            Component4 component4 = CDAFactory.eINSTANCE.createComponent4();
            component4.setObservation(buildNullResultObservation());
            organizer.getComponents().add(component4);
        }

        return organizer;
    }

    public Organizer buildNullResultOrganizer() {
        Organizer organizer = CDAFactory.eINSTANCE.createOrganizer();

        // Read the above comment for @classCode
        organizer.setClassCode(x_ActClassDocumentEntryOrganizer.BATTERY);
        organizer.setMoodCode(ActMood.EVN);

        II templateId = DatatypesFactory.eINSTANCE.createII();
        templateId.setRoot("2.16.840.1.113883.10.20.22.4.1");
        organizer.getTemplateIds().add(templateId);

        organizer.getIds().add(CcdUtils.getNullId());

        CE code = DatatypesFactory.eINSTANCE.createCE();
        code.setNullFlavor(NullFlavor.NI);
        organizer.setCode(code);

        CS statusCode = DatatypesFactory.eINSTANCE.createCS();
        statusCode.setNullFlavor(NullFlavor.NI);
        organizer.setStatusCode(statusCode);

        Component4 component4 = CDAFactory.eINSTANCE.createComponent4();
        component4.setObservation(buildNullResultObservation());
        organizer.getComponents().add(component4);

        return organizer;
    }

    public Observation buildResultObservation(ResultObservation resultObservation) {
        Observation o = CDAFactory.eINSTANCE.createObservation();

        o.setClassCode(ActClassObservation.OBS);
        o.setMoodCode(x_ActMoodDocumentObservation.EVN);

        II templateId = DatatypesFactory.eINSTANCE.createII();
        templateId.setRoot("2.16.840.1.113883.10.20.22.4.2");
        o.getTemplateIds().add(templateId);

        o.getIds().add(CcdUtils.getId(resultObservation.getId()));

        CE code = CcdUtils.createCE(resultObservation.getResultTypeCode());
        if (resultObservation.getText() != null) {
            String refId = ResultObservation.class.getSimpleName() + resultObservation.getId();
            ED originalText = DatatypesFactory.eINSTANCE.createED();
            TEL ref = DatatypesFactory.eINSTANCE.createTEL();
            ref.setValue("#" + refId);
            originalText.setReference(ref);
            code.setOriginalText(originalText);
        }
        o.setCode(code);

        CS statusCode = DatatypesFactory.eINSTANCE.createCS();
        if (resultObservation.getStatusCode() != null) {
            statusCode.setCode(resultObservation.getStatusCode());
        } else {
            statusCode.setNullFlavor(NullFlavor.NI);
        }
        o.setStatusCode(statusCode);

        o.setEffectiveTime(CcdUtils.createCenterTime(resultObservation.getEffectiveTime()));

        if (resultObservation.getMethodCode() != null) {
            CE methodCode = CcdUtils.createCE(resultObservation.getMethodCode());
            o.getMethodCodes().add(methodCode);
        }

        if (resultObservation.getTargetSiteCode() != null) {
            CD siteCode = CcdUtils.createCE(resultObservation.getTargetSiteCode());
            o.getTargetSiteCodes().add(siteCode);
        }

        if (resultObservation.getAuthor() != null) {
            o.getAuthors().add(SectionEntryFactory.buildAuthor(resultObservation.getAuthor()));
        }

        if (resultObservation.getInterpretationCodes() != null) {
            for (CcdCode interpretationCode : resultObservation.getInterpretationCodes()) {
                CE code1 = CcdUtils.createCE(interpretationCode);
                o.getInterpretationCodes().add(code1);
            }
        }

        SectionEntryFactory.initReferenceRanges(o, resultObservation.getReferenceRanges());

        if (resultObservation.getValue() != null && resultObservation.getValueUnit() != null) {
            PQ code1 = DatatypesFactory.eINSTANCE.createPQ();
            code1.setValue(BigDecimal.valueOf(resultObservation.getValue()));
            code1.setUnit(resultObservation.getValueUnit());
            // Value type is "PQ", from example
            o.getValues().add(code1);
        } else {
            o.getValues().add(CcdUtils.createNillCode());
        }

        return o;
    }

    public Observation buildNullResultObservation() {
        Observation o = CDAFactory.eINSTANCE.createObservation();

        o.setClassCode(ActClassObservation.OBS);
        o.setMoodCode(x_ActMoodDocumentObservation.EVN);

        II templateId = DatatypesFactory.eINSTANCE.createII();
        templateId.setRoot("2.16.840.1.113883.10.20.22.4.2");
        o.getTemplateIds().add(templateId);

        o.getIds().add(CcdUtils.getNullId());

        CE code = DatatypesFactory.eINSTANCE.createCE();
        code.setNullFlavor(NullFlavor.NI);
        o.setCode(code);

        // what statusCode?
        CS statusCode = DatatypesFactory.eINSTANCE.createCS();
        statusCode.setNullFlavor(NullFlavor.NI);
        o.setStatusCode(statusCode);

        o.setEffectiveTime(CcdUtils.getNullEffectiveTime());

        PQ code1 = DatatypesFactory.eINSTANCE.createPQ();
        code1.setNullFlavor(NullFlavor.NI);
        o.getValues().add(code1);

        return o;
    }

    private static String buildSectionText(Collection<Result> results) {

        if (CollectionUtils.isEmpty(results)) {
            return "No known results.";
        }

        StringBuilder sectionText = new StringBuilder();

        sectionText.append("<table>");
        sectionText.append("<thead>");
        sectionText.append("<tr>");
        sectionText.append("<th>Result Date</th>");
        sectionText.append("<th>Result Type</th>");
        sectionText.append("<th>Result Status</th>");
        sectionText.append("<th>Result Value</th>");
        sectionText.append("<th>Result Interpretations</th>");
        sectionText.append("<th>Result Reference Ranges</th>");
        sectionText.append("</tr>");
        sectionText.append("</thead>");
        sectionText.append("<tbody>");

        for (Result result : results) {
            if (result.getObservations() != null) {
                for (ResultObservation resultObservation : result.getObservations()) {
                    sectionText.append("<tr>");

                    CcdUtils.addDateCell(resultObservation.getEffectiveTime(), sectionText);

                    sectionText.append("<td>");
                    if (resultObservation.getText() != null) {
                        CcdUtils.addReferenceToSectionText(ResultObservation.class.getSimpleName() + resultObservation.getId(), resultObservation.getText(), sectionText);
                    } else {
                        CcdUtils.addEmptyCellToSectionText(sectionText);
                    }
                    sectionText.append("</td>");

                    sectionText.append("<td>");
                    if (resultObservation.getStatusCode() != null) {
                        sectionText.append(StringEscapeUtils.escapeHtml4(resultObservation.getStatusCode()));
                    } else {
                        CcdUtils.addEmptyCellToSectionText(sectionText);
                    }
                    sectionText.append("</td>");

                    sectionText.append("<td>");
                    if (resultObservation.getValue() != null && resultObservation.getValueUnit() != null) {
                        sectionText.append(StringEscapeUtils.escapeHtml4(resultObservation.getValue() + ", " + resultObservation.getValueUnit()));
                    } else {
                        CcdUtils.addEmptyCellToSectionText(sectionText);
                    }
                    sectionText.append("</td>");

                    sectionText.append("<td>");
                    if (resultObservation.getInterpretationCodes() != null) {
                        String prefix = "";
                        for (CcdCode interpretationCode : resultObservation.getInterpretationCodes()) {
                            if (interpretationCode.getDisplayName() != null) {
                                sectionText.append(prefix);
                                sectionText.append(StringEscapeUtils.escapeHtml4(interpretationCode.getDisplayName()));
                                prefix = "; ";
                            }
                        }
                    } else {
                        CcdUtils.addEmptyCellToSectionText(sectionText);
                    }
                    sectionText.append("</td>");

                    sectionText.append("<td>");
                    if (resultObservation.getReferenceRanges() != null) {
                        String prefix = "";
                        for (String referenceRange : resultObservation.getReferenceRanges()) {
                            sectionText.append(prefix);
                            sectionText.append(StringEscapeUtils.escapeHtml4(referenceRange));
                            prefix = "; ";
                        }
                    } else {
                        CcdUtils.addEmptyCellToSectionText(sectionText);
                    }
                    sectionText.append("</td>");

                    sectionText.append("</tr>");
                }
            }
        }

        sectionText.append("</tbody>");
        sectionText.append("</table>");

        return sectionText.toString();
    }

}