package com.scnsoft.eldermark.beans.reports.enums;

public enum ReportType {

    DEMOGRAPHICS,
    TIME_TO_COMPLETE_ASSESSMENT,
    IN_PERSON_TIME,
    PHONE_CALL_TIME,
    SERVICE_PLANS,
    HUD,
    HUD_MFSC,
    CLIENT_SERVICES,
    HOSPITALIZATIONS,
    COMPREHENSIVE,
    REFERRALS,
    COVID_19_LOG,
    CLIENT_INTAKES,
    ADL_REPORT,
    STAFF_CASELOAD,
    INSTITUTIONAL_RATE,
    CLIENT_PROGRAMS,
    IN_TUNE,
    ARIZONA_MATRIX,
    ARIZONA_MATRIX_MONTHLY,
    SIGNATURE_REQUESTS,
    EVENTS_NOTES,
    ECM_TRACKING,
    CS_TRACKING,
    CLIENT_EXPENSES,
    HOUSING_ASSESSMENT,
    OUTREACH_RETURN_TRACKER,
    OPT_IN_OUT
}
