import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CAREGIVER,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PHARMACIST_VENDOR,
  PREMIUM,
  SUPER_ADMINISTRATOR,
  VENDOR,
} from "../Roles";

const Feedback = lazy(() => import("containers/Events/workflow"));
const WorkflowEvents = lazy(() => import("containers/Events/WorkflowEvent/WorkflowEvent"));
const WorkflowAdminDetail = lazy(() => import("containers/Events/WorkflowAdminDetail/WorkflowAdminDetail"));

const QAFeedback = lazy(() => import("containers/Events/workflow"));
const QAWorkflowEvents = lazy(() => import("containers/Events/QAWorkflow/QAWorkflow"));
const QAWorkflowFeedback = lazy(() => import("containers/Events/WorkflowEvent/WorkflowFeedback/WorkflowFeedback"));
/*   admin role event */

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;
export default {
  component: Feedback,
  path: "/admin-events",
  permission: [
    SUPER_ADMINISTRATOR,
    BEHAVIORAL_HEALTH,
    ORGANIZATION_ADMIN,
    NAVI_GUIDE,
    VENDOR,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
  ],
  children: [
    {
      component: WorkflowEvents,
      path: "/",
      permission: [
        SUPER_ADMINISTRATOR,
        BEHAVIORAL_HEALTH,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        NAVI_GUIDE,
        ADMINISTRATOR,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
      ],
      exact: true,
    },
    {
      component: WorkflowAdminDetail,
      path: "/workflowDetail/:workflowId/:questionId/:fillClientId",
      permission: [
        SUPER_ADMINISTRATOR,
        BEHAVIORAL_HEALTH,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        NAVI_GUIDE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
      ],
    },
    // qaWorkflow的延申
    {
      component: QAFeedback,
      path: "/qa",
      permission: [
        SUPER_ADMINISTRATOR,
        BEHAVIORAL_HEALTH,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        NAVI_GUIDE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
      ],
      children: [
        {
          component: QAWorkflowEvents,
          path: "/events/:from",
          permission: [
            SUPER_ADMINISTRATOR,
            BEHAVIORAL_HEALTH,
            ORGANIZATION_ADMIN,
            VENDOR,
            DOCTOR,
            CAREGIVER,
            PREMIUM,
            CLINICIAN,
            PHARMACIST_VENDOR,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            NAVI_GUIDE,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            ...PROFESSIONALS_CARE_MANAGEMENT,
            ...PROFESSIONALS_OTHER,
            ...PHARMACY,
            ...NON_PROFESSIONALS,
            ...PROFESSIONALS_PRIMARY_PHYSICIAN,
          ],
          exact: true,
        },
        {
          component: WorkflowEvents,
          path: "/workflow-events",
          permission: [
            SUPER_ADMINISTRATOR,
            BEHAVIORAL_HEALTH,
            ORGANIZATION_ADMIN,
            VENDOR,
            DOCTOR,
            CAREGIVER,
            PREMIUM,
            CLINICIAN,
            PHARMACIST_VENDOR,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            NAVI_GUIDE,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            ...PROFESSIONALS_CARE_MANAGEMENT,
            ...PROFESSIONALS_OTHER,
            ...PHARMACY,
            ...NON_PROFESSIONALS,
            ...PROFESSIONALS_PRIMARY_PHYSICIAN,
          ],
          exact: true,
        },
        {
          component: QAWorkflowFeedback,
          path: "/feedback/:eventId",
          permission: [
            SUPER_ADMINISTRATOR,
            BEHAVIORAL_HEALTH,
            ORGANIZATION_ADMIN,
            VENDOR,
            DOCTOR,
            CAREGIVER,
            PREMIUM,
            CLINICIAN,
            PHARMACIST_VENDOR,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            NAVI_GUIDE,
            ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            ...PROFESSIONALS_CARE_MANAGEMENT,
            ...PROFESSIONALS_OTHER,
            ...PHARMACY,
            ...NON_PROFESSIONALS,
            ...PROFESSIONALS_PRIMARY_PHYSICIAN,
          ],
          exact: true,
        },
      ],
    },
  ],
};
