import { lazy } from "react";

import Organizations from "containers/Admin/Organizations/Organizations";
import Associations from "containers/Admin/Associations/Associations";
import Vendors from "containers/Admin/Vendors/Vendors";
import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  CONTENT_CREATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  VENDOR_CONCIERGE,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
} from "../Roles";

const Admin = lazy(() => import("containers/Admin/Admin"));
const WorkflowManagementCategories = lazy(
  () => import("containers/Admin/Workflow/WorkflowManagementCategories/WorkflowManagementCategories"),
);

const OrganizationDetails = lazy(
  () => import("containers/Admin/Organizations/OrganizationDetails/OrganizationDetails"),
);
const OrganizationCategories = lazy(
  () => import("containers/Admin/Organizations/OrganizationCategories/OrganizationCategories"),
);

const CommunityDetails = lazy(
  () => import("containers/Admin/Organizations/Communities/CommunityDetails/CommunityDetails"),
);
const CommunityHandsets = lazy(
  () => import("containers/Admin/Organizations/Communities/CommunityHandsets/CommunityHandsets"),
);
const CommunityZones = lazy(() => import("containers/Admin/Organizations/Communities/CommunityZones/CommunityZones"));
const CommunityLocations = lazy(
  () => import("containers/Admin/Organizations/Communities/CommunityLocations/CommunityLocations"),
);
const CommunityDeviceTypes = lazy(
  () => import("containers/Admin/Organizations/Communities/CommunityDeviceTypes/CommunityDeviceTypes"),
);

const Contacts = lazy(() => import("containers/Admin/Contacts/Contacts"));
const Fax = lazy(() => import("containers/Admin/Fax/Fax"));
const AuditLogs = lazy(() => import("containers/Admin/AuditLogs/AuditLogs"));
const WorkflowManager = lazy(() => import("containers/Admin/Workflow/WorkflowManager/WorkflowManager"));
const WorkflowManagementCreate = lazy(
  () => import("containers/Admin/Workflow/WorkflowManagementCreate/WorkflowManagementCreate"),
);
const WorkflowManagementPreview = lazy(
  () => import("containers/Admin/Workflow/WorkflowManagementCreate/WorkflowManagementPreview"),
);

const VendorDetails = lazy(() => import("containers/Admin/Vendors/VendorDetails/VendorDetail"));

const AssociationDetail = lazy(() => import("containers/Admin/Associations/AssociationDetail/AssociationDetail"));
const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Admin,
  path: "/admin",
  permission: [
    ADMINISTRATOR,
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    VENDOR,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    BEHAVIORAL_HEALTH,
    NAVI_GUIDE,
    QUALITY_ASSURANCE,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    PERSON_RECEIVING_SERVICES,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    CONTENT_CREATOR,
    VENDOR_CONCIERGE,
  ],
  children: [
    {
      component: Organizations,
      path: "/organizations",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: OrganizationDetails,
      path: "/organizations/:orgId",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: OrganizationCategories,
      path: "/organizations/:orgId/categories",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: CommunityDetails,
      path: "/organizations/:orgId/communities/:commId",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: CommunityHandsets,
      path: "/organizations/:orgId/communities/:commId/CommunityHandsets",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR_CONCIERGE,
      ],
    },
    {
      component: CommunityZones,
      path: "/organizations/:orgId/communities/:commId/zones",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR_CONCIERGE,
      ],
    },
    {
      component: CommunityLocations,
      path: "/organizations/:orgId/communities/:commId/locations",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR_CONCIERGE,
      ],
    },
    {
      component: CommunityDeviceTypes,
      path: "/organizations/:orgId/communities/:commId/device-types",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR_CONCIERGE,
      ],
    },
    {
      component: AuditLogs,
      path: "/audit-logs",

      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        BEHAVIORAL_HEALTH,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        QUALITY_ASSURANCE,
      ],
    },
    {
      component: Contacts,
      path: "/contacts",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        // VENDOR,
        // ASSOCIATION,
        // NON_CLINICAL_STAFF,
        // DOCTOR,
        // PHARMACIST_VENDOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        VENDOR_CONCIERGE,
      ],
    },
    {
      component: Associations,
      path: "/associations",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        BEHAVIORAL_HEALTH,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
      ],
      exact: true,
    },
    {
      component: AssociationDetail,
      path: "/associations/:assId",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        VENDOR,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
      ],
      exact: true,
    },
    {
      component: Vendors,
      path: "/vendors",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        CONTENT_CREATOR,
        // VENDOR_ADMIN,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: VendorDetails,
      path: "/vendors/:vendorId/:canEdit",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        CONTENT_CREATOR,
        // VENDOR_ADMIN,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    {
      component: Fax,
      path: "/fax",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        // VENDOR,
        // DOCTOR,
        // PHARMACIST_VENDOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        CONTENT_CREATOR,
        VENDOR_CONCIERGE,
      ],
      exact: true,
    },
    /*{
        component: Bids,
        path: '/bids',
        permission: [
            ADMINISTRATOR,
            SUPER_ADMINISTRATOR,
            COMMUNITY_ADMINISTRATOR,
            ...PROFESSIONALS_PRIMARY_PHYSICIAN,
            PERSON_RECEIVING_SERVICES,
            ...PROFESSIONALS_CARE_MANAGEMENT,
            ...PROFESSIONALS_OTHER,
            ...PHARMACY,
            ...NON_PROFESSIONALS,
            CONTENT_CREATOR
        ],
        exact: true,
    },*/
    // workflow
    {
      component: WorkflowManager,
      path: "/workflowManagement",
      permission: [ADMINISTRATOR, ORGANIZATION_ADMIN, SUPER_ADMINISTRATOR],
      exact: true,
    },
    {
      component: WorkflowManagementCategories,
      path: "/workflowManagement/categories/:organizationId",
      permission: [ADMINISTRATOR, ORGANIZATION_ADMIN, SUPER_ADMINISTRATOR],
      exact: true,
    },
    {
      component: WorkflowManagementCreate,
      path: "/workflowManagement/create",
      permission: [ADMINISTRATOR, ORGANIZATION_ADMIN, SUPER_ADMINISTRATOR],
      exact: true,
    },
    {
      component: WorkflowManagementPreview,
      path: "/workflowManagement/preview/:previewId/:isFromWorkflow",
      permission: [ADMINISTRATOR, ORGANIZATION_ADMIN, SUPER_ADMINISTRATOR],
      exact: true,
    },
  ],
};
