import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLIENT_POA,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
  ROLE_COMMUNITY_DOCTOR,
} from "../Roles";

const Messages = lazy(() => import("containers/Messages/Messages"));

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Messages,
  path: "/chats",
  permission: [
    SUPER_ADMINISTRATOR,
    BEHAVIORAL_HEALTH,
    ORGANIZATION_ADMIN,
    VENDOR,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    PERSON_RECEIVING_SERVICES,
    CLIENT_POA,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    ROLE_COMMUNITY_DOCTOR,
  ],
  exact: true,
};
