import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLIENT_POA,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  HOME_CARE_ASSISTANT,
  NAVI_GUIDE,
  NON_CLINICAL_STAFF,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  ROLE_COMMUNITY_DOCTOR,
} from "../Roles";

const Workflow = lazy(() => import("containers/Clients/Clients/Workflow/Workflow"));
const WorkflowDetail = lazy(() => import("containers/Clients/Clients/WorkflowDetail/WorkflowDetail"));
const Events = lazy(() => import("containers/Events/Events"));
const Clients = lazy(() => import("containers/Clients/Clients"));
const ClientList = lazy(() => import("containers/Clients/Clients/Clients"));
const Rides = lazy(() => import("containers/Clients/Clients/Rides/Rides"));
const CareTeam = lazy(() => import("containers/Clients/Clients/CareTeam/CareTeam"));
const ClientDashboard = lazy(() => import("containers/Clients/Clients/ClientDashboard/ClientDashboard"));
const Documents = lazy(() => import("containers/Clients/Clients/Documents/Documents"));
const Assessments = lazy(() => import("containers/Clients/Clients/Assessments/Assessments"));
const ServicePlans = lazy(() => import("containers/Clients/Clients/ServicePlans/ServicePlans"));
const CcdDocumentDetails = lazy(
  () => import("containers/Clients/Clients/Documents/CcdDocumentDetails/CcdDocumentDetails"),
);
const ClientCallHistory = lazy(() => import("containers/Clients/Clients/CallHistory/ClientCallHistory"));
const ClientExpenses = lazy(() => import("containers/Clients/Clients/Expenses/ClientExpenses"));

const Referrals = lazy(() => import("containers/Referrals/Referrals/Referrals"));
const ReferralDetails = lazy(() => import("containers/Referrals/ReferralDetails/ReferralDetails"));

const WorkflowAdminFillNow = lazy(
  () => import("containers/Clients/Clients/WorkflowAdminFillDetail/WorkflowAdminFillDetail"),
);

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Clients,
  path: "/clients",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    VENDOR,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    BEHAVIORAL_HEALTH,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    HOME_CARE_ASSISTANT,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    PERSON_RECEIVING_SERVICES,
    CLIENT_POA,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    ROLE_COMMUNITY_DOCTOR,
  ],
  children: [
    {
      component: ClientList,
      path: "/",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        HOME_CARE_ASSISTANT,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: ClientDashboard,
      path: "/:clientId",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: Events,
      path: "/:clientId/events",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: Documents,
      path: "/:clientId/documents",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: CcdDocumentDetails,
      path: "/:clientId/documents/:documentId-:documentTitle",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: Workflow,
      path: "/:clientId/workflow",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: WorkflowDetail,
      path: "/:clientId/workflow/:workflowId/:fillClientId/:preview",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: WorkflowAdminFillNow,
      path: "/:clientId/workflowDetail/:workflowId/:fillClientId",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        HOME_CARE_ASSISTANT,
        CLIENT_POA,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: CareTeam,
      path: "/:clientId/care-team",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        HOME_CARE_ASSISTANT,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: ServicePlans,
      path: "/:clientId/service-plans",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: Assessments,
      path: "/:clientId/assessments",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        HOME_CARE_ASSISTANT,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: Referrals,
      path: "/:clientId/outbound-referrals",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: ReferralDetails,
      path: "/:clientId/outbound-referrals/:referralId",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: Rides,
      path: "/:clientId/rides",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: ClientCallHistory,
      path: "/:clientId/call-history",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: ClientExpenses,
      path: "/:clientId/expenses",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PHARMACY,
        ...PROFESSIONALS_OTHER,
        ...NON_PROFESSIONALS,
      ],
    },
  ],
};
