import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
} from "../Roles";

const Documents = lazy(() => import("containers/Documents/Documents"));

const {
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_OTHER,
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Documents,
  path: "/company-documents",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    VENDOR,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    BEHAVIORAL_HEALTH,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...NON_PROFESSIONALS,
    ...PHARMACY,
  ],
};
