import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLIENT_POA,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
  VENDOR_ADMIN,
  ROLE_COMMUNITY_DOCTOR,
} from "../Roles";

import { path } from "lib/utils/ContextUtils";

const Help = lazy(() => import("containers/Help/Help"));
const ContactUs = lazy(() => import("containers/Help/ContactUs/ContactUs"));
const UserManuals = lazy(() => import("containers/Help/UserManuals/UserManuals"));
const ReleaseNotes = lazy(() => import("containers/Help/ReleaseNotes/ReleaseNotes"));

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Help,
  path: "/help",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    VENDOR,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    BEHAVIORAL_HEALTH,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    PERSON_RECEIVING_SERVICES,
    CLIENT_POA,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    VENDOR_ADMIN,
    ROLE_COMMUNITY_DOCTOR,
  ],
  children: [
    {
      component: ReleaseNotes,
      path: "/release-notes",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        VENDOR_ADMIN,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: UserManuals,
      path: "/user-manuals",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        VENDOR_ADMIN,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: ContactUs,
      path: "/contact-us",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        CLIENT_POA,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
        VENDOR_ADMIN,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      exact: true,
      redirect: {
        from: path("/help"),
        to: path("/help/user-manuals"),
      },
    },
  ],
};
