import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  NON_CLINICAL_STAFF,
  ORGANIZATION_ADMIN,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  ROLE_COMMUNITY_DOCTOR,
} from "../Roles";

const Referrals = lazy(() => import("containers/Referrals/Referrals"));
const ReferralList = lazy(() => import("containers/Referrals/Referrals/Referrals"));
const InquiryDetails = lazy(() => import("containers/Referrals/InquiryDetails/InquiryDetails"));
const ReferralDetails = lazy(() => import("containers/Referrals/ReferralDetails/ReferralDetails"));

const { PROFESSIONALS_CARE_MANAGEMENT, PROFESSIONALS_OTHER, PROFESSIONALS_PRIMARY_PHYSICIAN } = GROUPS;

export default {
  component: Referrals,
  path: "/inbound-referrals",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    VENDOR,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    BEHAVIORAL_HEALTH,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ROLE_COMMUNITY_DOCTOR,
  ],
  children: [
    {
      component: ReferralList,
      path: "/",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
      exact: true,
    },
    {
      component: ReferralDetails,
      path: "/:referralId/requests/:requestId",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
    {
      component: InquiryDetails,
      path: "/inquiries/:inquiryId",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ROLE_COMMUNITY_DOCTOR,
      ],
    },
  ],
};
