import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
} from "../Roles";

const Root = lazy(() => import("containers/PaperlessHealthcare/PaperlessHealthcare"));
const Home = lazy(() => import("containers/PaperlessHealthcare/PaperlessHealthcare/PaperlessHealthcare"));
const ConsentDetails = lazy(() => import("containers/PaperlessHealthcare/Consent/ConsentDetails"));
const PersonalDashboardDetails = lazy(
  () => import("containers/PaperlessHealthcare/PersonalDashboard/PersonalDashboardDetails"),
);
const TeamCareDetails = lazy(() => import("containers/PaperlessHealthcare/TeamCare/TeamCareDetails"));
const CommunicationsDetails = lazy(() => import("containers/PaperlessHealthcare/Communications/CommunicationsDetails"));
const DocumentsDetails = lazy(() => import("containers/PaperlessHealthcare/Documents/DocumentsDetails"));
const PharmacyMedicationsDetails = lazy(
  () => import("containers/PaperlessHealthcare/PharmacyMedications/PharmacyMedicationsDetails"),
);
const NotifyDetails = lazy(() => import("containers/PaperlessHealthcare/Notify/NotifyDetails"));
const NotifyFallDetectionDetails = lazy(
  () => import("containers/PaperlessHealthcare/NotifyFallDetection/NotifyFallDetectionDetails"),
);
const ReferralMarketplace = lazy(
  () => import("containers/PaperlessHealthcare/ReferralMarketplace/ReferralMarketplaceDetails"),
);
const ClinicalPharmacistDetails = lazy(
  () => import("containers/PaperlessHealthcare/ClinicalPharmacist/ClinicalPharmacistDetails"),
);
const NonEmergencyTransportation = lazy(
  () => import("containers/PaperlessHealthcare/NonEmergencyTransportation/NonEmergencyTransportationDetails"),
);
const HipaaCompliantCalendarDetails = lazy(
  () => import("containers/PaperlessHealthcare/HipaaCompliantCalendar/HipaaCompliantCalendarDetails"),
);

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  NON_PROFESSIONALS,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
} = GROUPS;

export default {
  component: Root,
  path: "/paperless-healthcare",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    NAVI_GUIDE,
    BEHAVIORAL_HEALTH,
    VENDOR,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    QUALITY_ASSURANCE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    PERSON_RECEIVING_SERVICES,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
  ],
  children: [
    {
      component: Home,
      path: "/",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: ConsentDetails,
      path: "/consent",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: PersonalDashboardDetails,
      path: "/personal-dashboard",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: TeamCareDetails,
      path: "/team-care",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: CommunicationsDetails,
      path: "/communications",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: DocumentsDetails,
      path: "/documents",
      permission: [
        SUPER_ADMINISTRATOR,
        ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: PharmacyMedicationsDetails,
      path: "/pharmacy-medications",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: NotifyDetails,
      path: "/notify",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: NotifyFallDetectionDetails,
      path: "/notify-fall-detection",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: ReferralMarketplace,
      path: "/referral-marketplace",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        QUALITY_ASSURANCE,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: ClinicalPharmacistDetails,
      path: "/clinical-pharmacist",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: NonEmergencyTransportation,
      path: "/non-emergency-transportation",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
    {
      component: HipaaCompliantCalendarDetails,
      path: "/hipaa-compliant-calendar",
      permission: [
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ADMINISTRATOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        PERSON_RECEIVING_SERVICES,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        ...NON_PROFESSIONALS,
      ],
      exact: true,
    },
  ],
};
