import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  CONTENT_CREATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PARENT_GUARDIAN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  QUALITY_ASSURANCE,
  SUPER_ADMINISTRATOR,
  VENDOR,
  ASSOCIATION,
  NON_CLINICAL_STAFF,
  ROLE_COMMUNITY_DOCTOR,
  CLIENT_POA,
} from "../Roles";
import BuildingDetail from "../../../containers/Marketplace/Components/Building/BuildingDetail/BuildingDetail";
import BuildingList from "../../../containers/Marketplace/Components/Building/BuildingList/BuildingList";

import VendorDetail from "../../../containers/Marketplace/Components/Vendor/VendorDetail/VendorDetail";

const Marketplace = lazy(() => import("containers/Marketplace/Marketplace"));
const MarketplaceHome = lazy(() => import("containers/Marketplace/Components/marketplacehome"));
const SimplyNexus = lazy(() => import("containers/Marketplace/Components/Nexus/nexus"));
const VendorList = lazy(() => import("containers/Marketplace/Components/Vendor/VendorV1/VendorList"));

const { PROFESSIONALS_CARE_MANAGEMENT, PROFESSIONALS_OTHER, PHARMACY, PROFESSIONALS_PRIMARY_PHYSICIAN } = GROUPS;

export default {
  component: Marketplace,
  path: "/marketplace",
  permission: [
    ADMINISTRATOR,
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    NAVI_GUIDE,
    ASSOCIATION,
    NON_CLINICAL_STAFF,
    BEHAVIORAL_HEALTH,
    VENDOR,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    COMMUNITY_ADMINISTRATOR,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    PERSON_RECEIVING_SERVICES,
    PARENT_GUARDIAN,
    CONTENT_CREATOR,
    QUALITY_ASSURANCE,
    ROLE_COMMUNITY_DOCTOR,
    CLIENT_POA,
  ],
  children: [
    {
      component: MarketplaceHome,
      path: "/",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },

    {
      component: SimplyNexus,
      path: "/simplyNexus",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },
    {
      component: BuildingDetail,
      path: "/buildingDetail/:communityId/:organizationId",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        BEHAVIORAL_HEALTH,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },
    {
      component: BuildingList,
      path: "/buildingList/:organizationId",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        BEHAVIORAL_HEALTH,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        VENDOR,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        CLINICIAN,
        PHARMACIST_VENDOR,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },
    {
      component: VendorDetail,
      path: "/vendorDetail/:id",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        PHARMACIST_VENDOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },
    {
      component: VendorList,
      path: "/vendorList",
      permission: [
        ADMINISTRATOR,
        SUPER_ADMINISTRATOR,
        ORGANIZATION_ADMIN,
        NAVI_GUIDE,
        BEHAVIORAL_HEALTH,
        VENDOR,
        ASSOCIATION,
        NON_CLINICAL_STAFF,
        DOCTOR,
        CAREGIVER,
        PREMIUM,
        PHARMACIST_VENDOR,
        COMMUNITY_ADMINISTRATOR,
        ...PROFESSIONALS_PRIMARY_PHYSICIAN,
        ...PROFESSIONALS_CARE_MANAGEMENT,
        ...PROFESSIONALS_OTHER,
        ...PHARMACY,
        PERSON_RECEIVING_SERVICES,
        PARENT_GUARDIAN,
        CONTENT_CREATOR,
        QUALITY_ASSURANCE,
        ROLE_COMMUNITY_DOCTOR,
        CLIENT_POA,
      ],
      exact: true,
    },
  ],
};
