import { lazy } from "react";

import {
  ADMINISTRATOR,
  BEHAVIORAL_HEALTH,
  CLINICIAN,
  COMMUNITY_ADMINISTRATOR,
  CONTENT_CREATOR,
  DOCTOR,
  CAREGIVER,
  PREMIUM,
  GROUPS,
  NAVI_GUIDE,
  ORGANIZATION_ADMIN,
  PERSON_RECEIVING_SERVICES,
  PHARMACIST_VENDOR,
  SUPER_ADMINISTRATOR,
  VENDOR,
} from "../Roles";

const SavedCommunities = lazy(() => import("containers/Marketplace/Private/SavedCommunities/SavedCommunities"));

const {
  PROFESSIONALS_CARE_MANAGEMENT,
  PROFESSIONALS_OTHER,
  PHARMACY,
  PROFESSIONALS_PRIMARY_PHYSICIAN,
  NON_PROFESSIONALS,
} = GROUPS;

export default {
  component: SavedCommunities,
  path: "/saved-for-later",
  permission: [
    SUPER_ADMINISTRATOR,
    ORGANIZATION_ADMIN,
    BEHAVIORAL_HEALTH,
    VENDOR,
    DOCTOR,
    CAREGIVER,
    PREMIUM,
    CLINICIAN,
    PHARMACIST_VENDOR,
    NAVI_GUIDE,
    ADMINISTRATOR,
    COMMUNITY_ADMINISTRATOR,
    PERSON_RECEIVING_SERVICES,
    ...PROFESSIONALS_PRIMARY_PHYSICIAN,
    ...PROFESSIONALS_CARE_MANAGEMENT,
    ...PROFESSIONALS_OTHER,
    ...PHARMACY,
    ...NON_PROFESSIONALS,
    CONTENT_CREATOR,
  ],
};
