package com.scnsoft.eldermark.service.document.templates.consol.factory.sections;

import com.scnsoft.eldermark.entity.Client;
import com.scnsoft.eldermark.entity.document.CcdCode;
import com.scnsoft.eldermark.entity.document.ccd.CodeSystem;
import com.scnsoft.eldermark.entity.document.ccd.Result;
import com.scnsoft.eldermark.entity.document.ccd.ResultObservation;
import com.scnsoft.eldermark.service.document.templates.cda.factory.sections.RequiredTemplateFactory;
import com.scnsoft.eldermark.service.document.templates.cda.factory.sections.SectionFactory;
import com.scnsoft.eldermark.service.document.templates.consol.factory.entries.ConsolSectionEntryFactory;
import com.scnsoft.eldermark.util.cda.CcdUtils;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;
import org.eclipse.mdht.uml.cda.CDAFactory;
import org.eclipse.mdht.uml.cda.Entry;
import org.eclipse.mdht.uml.hl7.datatypes.CE;
import org.eclipse.mdht.uml.hl7.datatypes.DatatypesFactory;
import org.eclipse.mdht.uml.hl7.datatypes.ST;
import org.openhealthtools.mdht.uml.cda.consol.ConsolFactory;
import org.openhealthtools.mdht.uml.cda.consol.ResultsSection;
import org.springframework.stereotype.Component;

import java.util.Collection;

/**
 * <h1>Results</h1> “This section contains the results of observations generated
 * by laboratories, imaging procedures, and other procedures ... The section may
 * contain all results for the period of time being summarized, but should
 * include notable results such as abnormal values or relevant trends.” [CCD
 * 3.13].
 * <p>
 * Laboratory results are typically generated by laboratories providing analytic
 * services in areas such as chemistry, hematology, serology, histology,
 * cytology, anatomic pathology, microbiology, and/or virology. These
 * observations are based on analysis of specimens obtained from the patient and
 * submitted to the laboratory. Imaging results are typically generated by a
 * clinician reviewing the output of an imaging procedure, such as where a
 * cardiologist reports the left ventricular ejection fraction based on the
 * review of a cardiac echocardiogram.
 * <p>
 * Procedure results are typically generated by a clinician to provide more
 * granular information about component observations made during a procedure,
 * such as where a gastroenterologist reports the size of a polyp observed
 * during a colonoscopy.
 *
 * @see Result
 * @see ResultObservation
 * @see CcdCode
 * @see Client
 */
@Component("consol.ResultsFactory")
public class ResultsFactory extends RequiredTemplateFactory implements SectionFactory<ResultsSection, Result> {

    // private static final String LEGACY_TABLE = "Results_NWHIN";
    private static final String TEMPLATE_ID_STR = "2.16.840.1.113883.10.20.22.2.3.1";
    private static ConsolSectionEntryFactory consolSectionEntryFactory = ConsolSectionEntryFactory.INSTANCE;

    @Override
    public ResultsSection buildTemplateInstance(Collection<Result> results) {
        final ResultsSection section = ConsolFactory.eINSTANCE.createResultsSection();
        section.getTemplateIds().add(DatatypesFactory.eINSTANCE.createII(TEMPLATE_ID_STR));

        CE sectionCode = CcdUtils.createCE("30954-2", "RESULTS", CodeSystem.LOINC);
        section.setCode(sectionCode);

        ST title = DatatypesFactory.eINSTANCE.createST();
        title.addText("Results");
        section.setTitle(title);

        section.createStrucDocText(buildSectionText(results));

        if (CollectionUtils.isEmpty(results)) {
            Entry entry = CDAFactory.eINSTANCE.createEntry();
            entry.setOrganizer(consolSectionEntryFactory.buildNullResultOrganizer());
            section.getEntries().add(entry);

            return section;
        }

        for (Result result : results) {
            Entry entry = CDAFactory.eINSTANCE.createEntry();
            entry.setOrganizer(consolSectionEntryFactory.buildResultOrganizer(result));
            section.getEntries().add(entry);
        }

        return section;
    }

    private static String buildSectionText(Collection<Result> results) {

        if (CollectionUtils.isEmpty(results)) {
            return "No known results.";
        }

        StringBuilder sectionText = new StringBuilder("<table>" +
                "<thead>" +
                "<tr>" +
                "<th>Result Date</th>" +
                "<th>Result Type</th>" +
                "<th>Result Status</th>" +
                "<th>Result Value</th>" +
                "<th>Result Interpretations</th>" +
                "<th>Result Reference Ranges</th>" +
                "</tr>" +
                "</thead>");

        var body = new StringBuilder();

        for (Result result : results) {
            if (CollectionUtils.isNotEmpty(result.getObservations())) {
                for (ResultObservation resultObservation : result.getObservations()) {
                    body.append("<tr>");

                    CcdUtils.addDateCell(resultObservation.getEffectiveTime(), body);

                    body.append("<td>");
                    if (resultObservation.getText() != null) {
                        CcdUtils.addReferenceToSectionText(
                                ResultObservation.class.getSimpleName() + resultObservation.getId(),
                                resultObservation.getText(), body);
                    } else {
                        CcdUtils.addEmptyCellToSectionText(body);
                    }
                    body.append("</td>");

                    body.append("<td>");
                    if (StringUtils.isNotEmpty(resultObservation.getStatusCode())) {
                        body.append(StringEscapeUtils.escapeHtml(resultObservation.getStatusCode()));
                    } else {
                        CcdUtils.addEmptyCellToSectionText(body);
                    }
                    body.append("</td>");

                    body.append("<td>");
                    if (resultObservation.getValue() != null && resultObservation.getValueUnit() != null) {
                        body.append(StringEscapeUtils
                                .escapeHtml(resultObservation.getValue() + ", " + resultObservation.getValueUnit()));
                    } else {
                        CcdUtils.addEmptyCellToSectionText(body);
                    }
                    body.append("</td>");

                    body.append("<td>");
                    if (CollectionUtils.isNotEmpty(resultObservation.getInterpretationCodes())) {
                        String prefix = "";
                        for (CcdCode interpretationCode : resultObservation.getInterpretationCodes()) {
                            if (interpretationCode.getDisplayName() != null) {
                                body.append(prefix);
                                body.append(StringEscapeUtils.escapeHtml(interpretationCode.getDisplayName()));
                                prefix = "; ";
                            }
                        }
                    } else {
                        CcdUtils.addEmptyCellToSectionText(body);
                    }
                    body.append("</td>");

                    body.append("<td>");
                    if (CollectionUtils.isNotEmpty(resultObservation.getReferenceRanges())) {
                        String prefix = "";
                        for (String referenceRange : resultObservation.getReferenceRanges()) {
                            body.append(prefix);
                            body.append(StringEscapeUtils.escapeHtml(referenceRange));
                            prefix = "; ";
                        }
                    } else {
                        CcdUtils.addEmptyCellToSectionText(body);
                    }
                    body.append("</td>");

                    body.append("</tr>");
                }
            }
        }

        if (body.length() == 0) {
            return "No known results.";
        }

        CcdUtils.addContent(sectionText, body, CcdUtils.ContentTag.TBODY);
        sectionText.append("</table>");

        return sectionText.toString();
    }
}