-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgc5togC6+HD6cUp/1
JicltWI1XZZwStOZzo0coGOXNlSgCgYIKoZIzj0DAQehRANCAASghOJ2SyqEOfs1
bwRVNB62nNTxqN+yegVNgIxx0zVGYogmN30KEh6O+2PoR9+3Lhmr+U0vg2F5lrJE
snDVZqmP
-----END PRIVATE KEY-----